### ISSUE TITLE
Fix python in docs that does not execute

### ISSUE THREAD

**Issue by ahonnecke** [vemel/mypy_boto3_builder#100]
Some of the code in the docs throws an error:
![image](https://user-images.githubusercontent.com/419355/126216336-b30f3887-6734-427c-9ea0-7054c0e5c4e6.png)

Here's a fix:
https://github.com/vemel/mypy_boto3_builder/pull/99

![image](https://user-images.githubusercontent.com/419355/126216404-03dbae19-12bc-4883-b749-1d5c7cb2a1b8.png)

**Comment by vemel** [comment]
Thank you for your PR! I will release a new micro release today, so your changes will be included.

**Comment by vemel** [comment]
Your changes are included in the latest `boto3-stubs` version. Thank you for your PR!
