### ISSUE TITLE
Using a dict instead of CreateBucketConfigurationTypeDef causes a warning in PyCharm

### ISSUE THREAD

**Issue by czechnology** [vemel/mypy_boto3_builder#102]
**The issue**
When calling `S3ServiceResource.create_bucket()`, using a valid dict as value for the `LocationConstraint` parameter results in an error in PyCharm:
> Expected type 'Optional[CreateBucketConfigurationTypeDef]', got 'Dict[str, str]' instead

As I understood the `TypedDict`, it should be equivalent to the dict, right? If I use `CreateBucketConfigurationTypeDef(LocationConstraint="eu-west-1")` as the parameter value instead, the check passes.

(Note that I'm new to boto3-stubs, so I might be misunderstanding the correct way to use it.)

Is this a PyCharm bug?

**To Reproduce**
1. Install 'boto3-stubs[s3]'
2. Display the following code sample in PyCharm

```python
import boto3
from mypy_boto3_s3.type_defs import CreateBucketConfigurationTypeDef

boto3.resource("s3").create_bucket(
    Bucket="bucket1",
    CreateBucketConfiguration={"LocationConstraint": "eu-west-1"},
)

boto3.resource("s3").create_bucket(
    Bucket="bucket2",
    CreateBucketConfiguration=CreateBucketConfigurationTypeDef(LocationConstraint="eu-west-1"),
)
```
3. How it looks in PyCharm
![image](https://user-images.githubusercontent.com/1052739/126896792-8d559934-b7ea-4bc2-8921-6bd508fefe33.png)

4. Running mypy on the above snippet produces no warnings.

**Additional context**
Windows, PyCharm 2021.1.3, `boto3-1.18.6`, `botocore-1.21.6`, `boto3-stubs-1.18.6`, `botocore-stubs-1.21.6`, `mypy-boto3-s3-1.18.6`

**Comment by vemel** [comment]
Hello!

Looks like a bug in PyCharm. I will take a look if it is possible to make `boto3-stubs` comnpatible with PyCharm-style TypedDicts, but I am not sure. This bug was also present in the old `Jedi` LSP for VSCode.

**Comment by czechnology** [comment]
Thanks, Vlad!

**Comment by vemel** [comment]
I have just cross-checked this on `PyCharm 2021.3.2` and it works as expected, so JetBrains fixed the issue. Thank you for the report!

```python
import boto3
from mypy_boto3_s3.type_defs import CreateBucketConfigurationTypeDef

boto3.resource("s3").create_bucket(
    Bucket="bucket1",
    CreateBucketConfiguration={"LocationConstraint": "eu-west-1"}, # no issues
)

boto3.resource("s3").create_bucket(
    Bucket="bucket1",
    CreateBucketConfiguration={"LocationConstraint1": "eu-west-1"}, # Expected type 'CreateBucketConfigurationTypeDef', got 'dict[str, str]' instead
)

boto3.resource("s3").create_bucket(
    Bucket="bucket2",
    CreateBucketConfiguration=CreateBucketConfigurationTypeDef(LocationConstraint="eu-west-1"), # no issues
)

```
