### ISSUE TITLE
Return type annotations does not work in PyCharm autocomplete

### ISSUE THREAD

**Issue by takeda** [vemel/mypy_boto3_builder#111]
**Describe your idea**
Whenever I'm working with boto3 I create models using pydantic to match the results returned by functions. This adds additional type information and makes working with results much easier (autocomplete, easy refactoring and highlighting of errors).
Unfortunately this is prone to errors (certain fields in AWS responses aren't always provided, so one has to know when to use Optional) and tedious. I'm wondering if it could be in the scope of this project to provide that. Ideally, this should be provided by boto3 package, but if they would be open to feature requests the types would were built in and this project would be unnecessary :/

Since pydantic is an extra dependency perhaps dataclasses or typed named tuples could be used.

**Code sample**
This is example how I use pydantic models, but maybe there's a better way:
```python
target_health: Final = ELBv2DescribeTargetHealth(
    **self.client.describe_target_health(TargetGroupArn=target_arn)
)

return frozenset(
    description.Target.Id
    for description in target_health.TargetHealthDescriptions
    if description.TargetHealth.State != "draining"
)
```

**Comment by vemel** [comment]
Hello!

`boto3-stubs` already has type annotations for return values. Both `mypy` and `pyright` can be used to check if you use return values properly and even respect optional fields.

This is a documentation for `describe_target_health` method: https://github.com/vemel/boto3_stubs_docs/blob/master/mypy_boto3_elbv2/client.md#describe_target_health

Return value is described here: https://github.com/vemel/boto3_stubs_docs/blob/master/mypy_boto3_elbv2/type_defs.md#describetargethealthoutputtypedef 

Please let me know if you find in helpful or you have any ideas on how to improve it.

**Comment by takeda** [comment]
Yes, that works when checking and it is great, the problem is that IDEs like PyCharm appear to ignore it and an user doesn't get benefits of autocomplete. If the values are presented as attributes instead of dictionaries it is much nicer to work with them.

I understand though that this perhaps is out of the scope of this package, and other places of fixing it would be better. For example PyCharm should a special treatment for the `TypedDict` or `boto3` should just return attributes.

**Comment by vemel** [comment]
I did some testing with `PyCharm`. it looks like it stops type annotations discovery at some point, probably due to low RAM. New `boto3-stubs` version will use `typing-extensions.TypedDict` instead of `typing.TypedDict`, probably it will fix or at least affect the issue.

**Comment by vemel** [comment]
Please open a ticket. Thank you! I leave this issue open for now.

**Comment by vemel** [comment]
Looks like PyCharm team has finally fixed the issue. I have just tested it on `PyCharm 2021.3.2`

```python
import boto3
from mypy_boto3_s3.client import S3Client

client: S3Client = boto3.client("s3")
response = client.create_bucket(Bucket="bucket", Key="key")
location = response["Location"]  # location revealed type is correct - str
```

Closing the issue, but let me know if not all response types are covered by PyCharm.
