### ISSUE TITLE
Clarify newversion issue so that we can build on conda-forge

### ISSUE THREAD

**Issue by maresb** [vemel/mypy_boto3_builder#117]
I cannot produce the conda-forge package for mypy_boto3_builder because it is [blocked](https://github.com/conda-forge/mypy_boto3_builder-feedstock/pull/33#issuecomment-962474503) by an [outstanding question](https://github.com/conda-forge/staged-recipes/pull/16764#discussion_r742793302) regarding your [newversion fork](https://github.com/vemel/newversion), which is a dependency.

Additionally, it seems that the GitHub "Issues" pages on your newversion fork is disabled, so I can't create a corresponding issue there.

**Comment by vemel** [comment]
Hello!

Thanks for letting me know. I have opened `Issues` and responded to the question. 

Please let me know if there is anything left to be done.
