### ISSUE TITLE
Missing `Optional`s on `Session` arguments

### ISSUE THREAD

**Issue by adamnovak** [vemel/mypy_boto3_builder#120]
In `boto3-stubs` version `1.20.33`, the stubs for `Session`'s `__init__` look like this:

```
class Session:
    def __init__(
        self,
        aws_access_key_id: str = None,
        aws_secret_access_key: str = None,
        aws_session_token: str = None,
        region_name: str = None,
        botocore_session: BotocoreSession = None,
        profile_name: str = None,
    ):
```

But the Session definition in Boto3 looks like:

```
    def __init__(self, aws_access_key_id=None, aws_secret_access_key=None,
                 aws_session_token=None, region_name=None,
                 botocore_session=None, profile_name=None):
```

Because these are all defined as normal keyword arguments with default `None` values (and not being read out of `**kwargs`), it is safe to pass an `Optional[str]` (or `Optional[BotocoreSession]` as applicable) to all of these. But the type stubs don't capture this.

These arguments of this constructor need to be added to the manually-maintained list mentioned in #64.

**Comment by vemel** [comment]
Thank you for the report!

I have included a fix to [mypy-boto3-buuilder 6.3.2](https://github.com/vemel/mypy_boto3_builder/releases/tag/6.3.2). New `boto3-stubs 1.20.35` should be out in 1 or 2 hours, so please try it out and let me know if it works for you as expected.
