### ISSUE TITLE
AWS docs (and the stubs) think `IAM.InstanceProfile` has a `roles` (plural) field of type `Role` (singular)

### ISSUE THREAD

**Issue by adamnovak** [vemel/mypy_boto3_builder#122]
Here it is in the official docs, as of boto3 1.20.33: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html?highlight=detach_policy#IAM.InstanceProfile.roles

This makes it so when I try to do this:

```
    instance_profile = iam_resource.InstanceProfile(instance_profile_name)
    for role in instance_profile.roles:
        instance_profile.remove_role(RoleName=role.name)
```

I get this:

```
src/toil/lib/aws/utils.py: note: In function "delete_iam_instance_profile":
src/toil/lib/aws/utils.py:78:17: error: "Role" has no attribute "__iter__" (not
iterable)  [attr-defined]
        for role in instance_profile.roles:
                    ^
```

I think this might really be a bug on Amazon's side in whatever the generator is working from; it makes no sense for this to just be a single role.

This is with boto3-stubs 1.20.33.

Is this sort of thing something the generator is expected to be able to work around?

**Comment by vemel** [comment]
It is not a bug, but a naming issue. `IAM.InstanceProfile.roles` is just a `Role`: https://github.com/vemel/boto3_stubs_docs/blob/master/mypy_boto3_iam/service_resource.md#instanceprofile

**Comment by adamnovak** [comment]
> `IAM.InstanceProfile.roles` is just a `Role`

I don't see how that can be true. The [underlying `GetInstanceProfile` API call](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetInstanceProfile.html) shows an example where `<Roles>` in the response XML is an array (though with just one `<member>` element in this example), and the [docs for the type](https://docs.aws.amazon.com/IAM/latest/APIReference/API_InstanceProfile.html) document that the `InstanceProfile` will have an "Array of Role objects". Semantically, instance profiles can have multiple roles at once. Roles can be added and deleted, and there's no clear reason why the API would be limited to returning one of those roles at a time.

Boto3 itself defines the field here in its JSON spec for what types it should create: https://github.com/boto/boto3/blob/0b82bf9843ad6d350b48442c47f4a484a886ee3f/boto3/data/iam/2010-05-08/resources-1.json#L732-L742

That looks like it's meant to define an array-type field to me. I think it's incorrectly under "has" instead of "hasMany" in Boto3. Maybe that means Boto3 actually does return a single value from the array it gets from the server?

**Comment by adamnovak** [comment]
@vemel I tested this manually, and the `boto3` module does in fact return a list here. I happen to have an instance profile named `ecsInstanceRole`, as reported by `aws iam list-instance-profiles`, so I ran this:

```
python3 <<'EOF'
import boto3
iam = boto3.resource('iam')
instance_profile = iam.InstanceProfile('ecsInstanceRole')
print(instance_profile.roles)
EOF
```

And I got this:

```
Enter MFA code for arn:aws:iam::652235167018:mfa/anovak@soe.ucsc.edu: 
[iam.Role(name='ecsInstanceRole')]
```

So the actual value of the `roles` property comes out as a list, contrary to what the docs and spec seem to suggest.

**Comment by vemel** [comment]
Well, if it is a mixin from boto3 I should add a custom stub for this case. Will take a look tomorrow. Thank you for the investigation

**Comment by vemel** [comment]
So, it is not a mixin, but a documentation/boto3 generation error. Looks like boto3 resource references could be lists, but it is not mentioned explicitly anywhere. I was able to identify those references as lists because they have `[]` in `reference.resource.path` (e.g. `Roles[]`).

During fixing this issue, I found out that resource attributes do not retrieve types from botocore shapes and rely only on docs. I fixed this as well.

Since these two fixes potentially affect many services, I am going to cross-check everything during the weekend and release all services along with `boto3-stubs==1.20.46.post1`

**Comment by mr-c** [comment]
I can confirm the type fix in `boto3-stubs==1.20.46.post1` for the same codebase that @adamnovak was using; thanks!

**Comment by vemel** [comment]
@mr-c awesome! Please let me know if there is anything else related to this issue. Turns out, resource type annotations still has some issues.

**Comment by adamnovak** [comment]
Thanks for fixing this! Sorry to show up with so many complaints; these stubs are a really useful thing for us!
