### ISSUE TITLE
`ObjectVersionTypeDef` and `DeleteMarkerEntryTypeDef` should share a base type

### ISSUE THREAD

**Issue by adamnovak** [vemel/mypy_boto3_builder#123]
**Describe your idea**
I'm deleting a bucket with versioning enabled. To do this, I need to get all the object versions and all the delete markers in the bucket, and delete them.

They types share `Owner`, `Key`, `VersionID`, `IsLatest`, and `LastModified` keys, and they arrive alongside each other on each page of a `list_object_versions` paginator, but I'm not allowed to concatenate lists of them together, presumably because they don't share a base type?

```
ObjectVersionTypeDef = TypedDict(
    "ObjectVersionTypeDef",
    {
        "ETag": str,
        "Size": int,
        "StorageClass": Literal["STANDARD"],
        "Key": str,
        "VersionId": str,
        "IsLatest": bool,
        "LastModified": datetime,
        "Owner": "OwnerTypeDef",
    },
    total=False,
)
```

```
DeleteMarkerEntryTypeDef = TypedDict(
    "DeleteMarkerEntryTypeDef",
    {
        "Owner": "OwnerTypeDef",
        "Key": str,
        "VersionId": str,
        "IsLatest": bool,
        "LastModified": datetime,
    },
    total=False,
)
```

They probably should both extend a `VersionedBucketEntryTypeDef` or something.

**Code sample**

```
    s3_client = ...
    paginator = s3_client.get_paginator('list_object_versions')
    try:
        for response in paginator.paginate(Bucket=bucket):
            # Versions and delete markers can both go in here to be deleted
            to_delete: List[VersionedBucketEntryTypeDef] = response.get('Versions', []) + response.get('DeleteMarkers', [])
            for entry in to_delete:
                s3_client.delete_object(Bucket=bucket, Key=entry['Key'], VersionId=entry['VersionId'])
        s3_resource.Bucket(bucket).delete()
```

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.

Ubuntu 20.04, boto3 1.17.57, boto3-stubs 1.20.33

**Comment by vemel** [comment]
Well, even if `TypedDict`s share the same base type, you are not allowed to concatenate lists of them. At least according to https://www.python.org/dev/peps/pep-0589/

I think that both `mypy` and `pyright` follow this PEP.

I would recommend creating a new `List[DeleteMarkerEntryTypeDef]` and populating it manually.

Please let me know if it was helpful.

**Comment by adamnovak** [comment]
What I want to do is cast my lists of the two derived types to be lists of the base type, and then concatenate those two lists of the base type together.

Looking at PEP-589 leads me to believe that `DeleteMarkerEntryTypeDef` *is* actually going to be understood as a base of `ObjectVersionTypeDef` by MyPy, because compatibility is all defined in terms of the sets of keys and their types. So maybe I can downcast the one list to the type of the other.
