### ISSUE TITLE
Typos of `boto-stubs` instead of `boto3-stubs`

### ISSUE THREAD

**Issue by daveisfera** [vemel/mypy_boto3_builder#124]
**Describe the bug**
There are a few locations that say `boto-stubs` instead of `boto3-stubs`, like [this one](https://github.com/vemel/mypy_boto3_builder/tree/master/types_boto3#vscode)

**To Reproduce**
N/A

**Comment by vemel** [comment]
Thank you for the report! FIxed everywhere, this typo was even in auto-generated docs.
