### ISSUE TITLE
s3.Bucket.objectsCollection.delete() returns List not DeleteObjectsOutputTypeDef

### ISSUE THREAD

**Issue by tekumara** [vemel/mypy_boto3_builder#126]
**Describe the bug**
s3.Bucket.objectsCollection.delete() returns List not DeleteObjectsOutputTypeDef

**To Reproduce**

```python
import boto3
bucket = 'mybucket'
folder = 'myfolder'
s3 = boto3.resource('s3')
bucket_res = s3.Bucket(bucket)
response = bucket_res.objects.filter(Prefix=folder).delete()
# response is actually List[DeleteObjectsOutputTypeDef], not
# DeleteObjectsOutputTypeDef as the type stub (and docs) suggests
print(len(response[0]['Deleted']))
```
Actual pyright output

```
test.py:9:11 - error: Could not access item in TypedDict
    "Literal[0]" is not a string literal
```

**Expected pyright output**

No errors

**Additional context**

```
boto3                      1.20.47
boto3-stubs                1.20.47
botocore                   1.23.47
botocore-stubs             1.23.47
mypy-boto3-s3              1.20.46.post1
```

**Comment by vemel** [comment]
Thank you for the report!

I have released a fix, now all collection batch methods return `List[ResponseTypeDef]`. I am going to release all service packages tonight with `boto3-stubs==1.12.48`.

**Comment by vemel** [comment]
Well, the new version is finally released: https://pypi.org/project/mypy-boto3-s3/

Please let me know if it works for you as expected.

**Comment by tekumara** [comment]
Can confirm this works, thanks @vemel for the speedy response!
