### ISSUE TITLE
aiobotocore: paginate() might not be async?

### ISSUE THREAD

**Issue by takeda** [vemel/mypy_boto3_builder#129]
**Describe the bug**
I installed types-aiobotocore and started using them (thank you BTW).

I have the following line highlighted as error in PyCharm:
```py
		async with self.b3_session.client("ec2") as client:  # type: types_aiobotocore_ec2.Client
			async for result in client.get_paginator("describe_vpc_endpoint_connections").paginate(Filters=dict2namevalues({"service-id": [vpc_service_id]})):
                             ...

```

The error is:
```
Expected type 'collections.AsyncIterable', got 'Coroutine[Any, Any, _PageIterator[DescribeVpcEndpointConnectionsResultTypeDef]]' instead 
```

The above code works, I believe paginator() is not async and instead is an object with __aiter__().

This happens in the latest version currently: 2.1.0.post2

**Comment by vemel** [comment]
Thank you for the report!

Now `AioPaginator.paginate` returns `AsyncIterable` with original type. We still have no integration tests for `types-aiobotocore`, but I checked manually that it works now.

Please let me know if new version `types-aiobotocore 2.1.1` works for you as it should.

**Comment by takeda** [comment]
@vemel Sorry for the delay. I checked and this resolved my issue. Thank you.
