### ISSUE TITLE
Botocore-stubs name is not importable

### ISSUE THREAD

**Issue by ofekengel** [vemel/mypy_boto3_builder#130]
When installing `botocore-stubs==1.23.54` the folder name in `site-packages` is `botocore-stubs`.
This causes Pycharm (2021.2 professional) to not recognize the package.
![image](https://user-images.githubusercontent.com/62753203/153896838-53ffd7d7-0543-43f6-a9f7-2ca7f5bcdc40.png)
![image](https://user-images.githubusercontent.com/62753203/153897182-077cf554-01e8-4fa0-9c40-fcd157347b1e.png)

Renaming the directory seems solves the issue.
![image](https://user-images.githubusercontent.com/62753203/153896703-41db22ab-a0d1-4c56-9ebd-1af235684152.png)

1. Install 'botocore-stubs'
2.  Attempt importing the module in Pycharm

MacOS BigSur 11.5.2, pip installation.

**Comment by vemel** [comment]
Hello!

`botocore-stubs` is not meant to be importable, it only provides type annotations for `botocore`. You should use `botocore` for imports and type checking and code completion should work

```python
from botocore.config import Config

c = Config(...)
# PyCharm should show arguments and types correctly
# and provide type checking
```

Let me know if code completion and type checking do not work for you with installed `botocore-stubs`.

**Comment by skeggse** [comment]
<img width="773" alt="image" src="https://github.com/youtype/mypy_boto3_builder/assets/1348991/0eb294b4-6a94-4bae-bd2e-e92e628a7113">

Is there a way to import the `TypedDict` definitions for some of the `Config` parameters to avoid the issue of a `dict` not being compatible with the expected type?
