### ISSUE TITLE
Enabling bucket versioning doesn't appear to require any parameters

### ISSUE THREAD

**Issue by takeda** [vemel/mypy_boto3_builder#138]
**Describe the bug**

```python
boto3.resource('s3').BucketVersioning(name).enable()
```

displays:
```
error: Missing named argument "VersioningConfiguration" for "enable" of "BucketVersioning"
```

I see that https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketVersioning.html#API_PutBucketVersioning_RequestSyntax says that this parameter is required, but I have code to which I'm adding types and looks like not providing them works as well.

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.

Mac, `poetry add -D 'boto3-stubs[dynamodb,s3]'`, 1.21.23

**Comment by vemel** [comment]
Hello! THank you for the report.

This is a bug. `VersioningConfiguration` is passed to the method from the resource. I should exclude this argument from argument list completely.

**Comment by vemel** [comment]
There is a new release with the fix and tons of other stuff: https://github.com/vemel/mypy_boto3_builder/releases/tag/7.4.0

Please let me know if it works for you as it should.

Tech details:

`BucketVersioning.enable` and `BucketVersioning.suspend` shapes have identifier that sets `VersioningConfiguration.Status`. So, looks like in this case `VersioningConfiguration` argument should be completely removed from an initializer completely. This argument is still required in `BucketVersioning.put` method.

**Comment by takeda** [comment]
Yes, that resolved this issue. Thank you.

I have another one, if you want I can open a new ticket.

```python
...
session = boto3.Session(region_name=region)
...
s3_client = session.client("s3")
current_region = session.region_name
s3_client.create_bucket(
    Bucket=name,
    ACL="private",
    CreateBucketConfiguration={"LocationConstraint": current_region},
)
```

When mypy runs with `--strict` it shows:

```
error: Incompatible types (expression has type "str", TypedDict item "LocationConstraint" has type "Literal['EU', 'af-south-1', 'ap-east-1', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'cn-north-1', 'cn-northwest-1', 'eu-central-1', 'eu-north-1', 'eu-south-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'me-south-1', 'sa-east-1', 'us-east-2', 'us-gov-east-1', 'us-gov-west-1', 'us-west-1', 'us-west-2']")
```

**Comment by vemel** [comment]
This is not related. The issue is that [CreateBucketConfiguration](https://vemel.github.io/boto3_stubs_docs/mypy_boto3_s3/type_defs.html#createbucketconfigurationtypedef) does not accept any string in `LocationConstraint`, only [BucketLocationConstraintType](https://vemel.github.io/boto3_stubs_docs/mypy_boto3_s3/literals.html#bucketlocationconstrainttype)

I can probably set a Literal type for `Session.region_name`, but I am not sure that these literals will match perfectly.

For now, you can cast a type or type-ignore:

```python
from mypy_boto3_s3.literals import BucketLocationConstraintType
from typing import cast

# cast
current_region = cast(BucketLocationConstraintType, session.region_name)

# or type ignore
current_region: BucketLocationConstraintType = session.region_name  # type: ignore
```

I will check if it makes sense to convert `Session.region_name` to a Literal.

**Comment by vemel** [comment]
@takeda See #140 . And let me know if it works for you as intended.

**Comment by vemel** [comment]
https://github.com/boto/botocore/issues/2648
