### ISSUE TITLE
ImportError: cannot import name 'NotRequired' from 'typing_extensions'

### ISSUE THREAD

**Issue by 1-900-MIXALOT** [vemel/mypy_boto3_builder#139]
**Describe the bug**

Getting an import error with latest release:

```
    from .client import DynamoDBClient

/usr/local/lib/python3.7/site-packages/mypy_boto3_dynamodb/client.py:36: in <module>

    from .paginator import (

/usr/local/lib/python3.7/site-packages/mypy_boto3_dynamodb/paginator.py:43: in <module>

    from .type_defs import (

/usr/local/lib/python3.7/site-packages/mypy_boto3_dynamodb/type_defs.py:20: in <module>

    from typing_extensions import NotRequired

E   ImportError: cannot import name 'NotRequired' from 'typing_extensions' (/usr/local/lib/python3.7/site-packages/typing_extensions.py)

```

version 1.21.23

**Comment by vemel** [comment]
Hello!

Please update `typing-extensions` to `4.1.1`. I did not put a version constraint, looks like I should add it.

**Comment by vemel** [comment]
I have just released `builder 7.4.1`, which has a `typing-extensions` version constraint.

A new `boto3-stubs` release should be uploaded soon. The only change is a version requirement.

**Comment by 1-900-MIXALOT** [comment]
Okay, my CI run has a new error:
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/typing_extensions-3.10.0.1.dist-info/METADATA'

```
I'll try and look more tomorrow. Thanks for the quick follow up!

**Comment by vemel** [comment]
Hmm, looks like your `site-packages` are broken. Try to uninstall `typing-extensions` and install again
```bash
sudo pip uninstall typing-extensions # probably run the command multiple times

sudo pip install -U typing-extensions
```

Even if you have a package that depends on `typing-extensions 3.x`, version `4.x` is fully compatible and should work properly.

**Comment by 1-900-MIXALOT** [comment]
Updating typing-extensions appears to have solved my issue. TY!
