### ISSUE TITLE
Installing the stubs as extras does not correctly set the version for packages

### ISSUE THREAD

**Issue by mskrip** [vemel/mypy_boto3_builder#141]
**Describe the bug**

When installing the stubs as extras with a specific version locked, for example `boto3-stubs[cognito-idp]==1.19.2` installs the `mypy-boto3-cognito-idp` package with condition `>=1.19.0`, which as of now installs the latest `1.21.27`.

This became problematic for us as [Pydantic does not yet support NotRequired TypedDict option](https://github.com/samuelcolvin/pydantic/issues/3859) introduced in one of the latest versions of the stubs which broke our application, even though we have the `boto3-stubs` package locked to a specific version.

**To Reproduce**

1. Run  'pip install boto3-stubs[cognito-idp]==1.19.2'
2. A package `mypy-boto3-cognito-idp==1.21.27` is installed

**Expected state**

The `mypy-boto3-cognito-idp` package should be installed with the specified version (`1.19.2`)

**Additional context**

- Linux 5.17.1-arch1-1
- any `boto3-stubs` installation method (tried with pip and poetry)
- `boto3` version - not relevant

**Comment by vemel** [comment]
@mskrip there are two ways you can solve the issue:
- `pip install 'boto3-stubs[cognito-idp]==1.19.12.post1'` - it limits sub packages version to `<1.20.0`
- Or just use latest `boto3-stubs[cognito-idp]`, I have fixed `pydantic` compatibility

**Comment by mskrip** [comment]
Wow, thank you very much for the prompt response and fix, I've opted in to go with the latest version and it works. Thanks again :)
