### ISSUE TITLE
[BUG]  `Module has no attribute "client"`

### ISSUE THREAD

**Issue by jbpratt78** [vemel/mypy_boto3_builder#15]
**Describe the bug**
`Module has no attribute "client"`

**To Reproduce**
1. Install 'boto3-stubs[...]'
2.  Run mypy on the following code sample

```python
import boto3
s3_client = boto3.client("s3")
...
```
3. Actual mypy output

```
$ python -m mypy src/app.py
src/app.py:8: error: Skipping analyzing 'botocore.exceptions': found module but no type hints or library stubs
src/app.py:8: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
src/app.py:12: error: Module 'mypy_boto3_sts' has no attribute 'ClientAssumeRoleResponseCredentialsTypeDef'
src/app.py:20: error: Module has no attribute "client"
src/app.py:30: error: Incompatible types in assignment (expression has type "Optional[ClientAssumeRoleResponseCredentialsTypeDef]", variable has type "Dict[Any, Any]")
src/app.py:34: error: Module has no attribute "client"
Found 5 errors in 1 file (checked 1 source file)
```

**Expected mypy-output**

```
...
```

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.
```
$ python -m pip show boto3-stubs
Name: boto3-stubs
Version: 1.12.33.0
Summary: Type annotations for boto3 1.12.33, generated by mypy-boto3-buider 1.0.6

$ python -m pip show boto3
Name: boto3
Version: 1.12.19
Summary: The AWS SDK for Python
```
I also noticed this issue https://github.com/vemel/mypy_boto3/issues/12 but I am still having problems. I honestly think this may be a problem on my end but wanted to open an issue to be sure.

**Comment by vemel** [comment]
Looks like type definitions were built incorrectly for sts. I should add this service to integration tests. Thank you!

**Comment by vemel** [comment]
Actually, try to run `mypy_boto3`. Probably you not have generated index packages.

**Comment by vemel** [comment]
Actually, you are probably missing auto-generated index files.

Try installing the package this way:

```bash
pip install 'boto3-stubs[sts]'

# rebuild index just in case
python -m mypy_boto3
```

**Comment by maxcountryman** [comment]
I'm running into this same issue where I have:

```python
import boto3
from mypy_boto3_sts import sts

sts_client: sts.STSClient = boto3.client("sts")
```

But then `mypy` complains: `error: Module has no attribute "client"`.
