### ISSUE TITLE
[BUG] boto3-stubs 1.12.33 does not provide the extra 'mypy-boto3-rds-data'

### ISSUE THREAD

**Issue by mulka** [vemel/mypy_boto3_builder#17]
**Describe the bug**
I'm trying to use this for rds-data, but getting this error when running the pip install:
  boto3-stubs 1.12.33 does not provide the extra 'mypy-boto3-rds-data'

**To Reproduce**
1. pip install 'boto3-stubs[mypy-boto3-rds-data]' 

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.
macOS Catalina
boto3==1.12.33

**Comment by vemel** [comment]
I will add to the next release. Thank you for the report!

**Comment by vemel** [comment]
Actually, I just noticed that extra name is incorrect, it should be

```bash
pip install 'boto3-stubs[rds-data]'
```

You can find all supported extras in readme https://pypi.org/project/boto3-stubs/

**Comment by mulka** [comment]
Ok, maybe this documentation needs to be updated: https://pypi.org/project/mypy-boto3-rds-data/

**Comment by vemel** [comment]
Yes, thank you!

**Comment by vemel** [comment]
Docs updated for all packages, thank you for the report.
