### ISSUE TITLE
[BUG] Installing mypy_boto3_builder causes Pycharm to lag

### ISSUE THREAD

**Issue by mWozDev** [vemel/mypy_boto3_builder#18]
**Describe the bug**
When installing the stubs (in my case specifically just the EC2 ones without any other S3 services), Pycharm grinds to a halt and is unusable. I've left it running for an hour to ensure there's no indexing/recaching occurring and the issues persists.

**This is most likely a Pycharm issue but I thought I would post here anyway in case someone else has run into it.**

Thanks so much for putting this package together!

**To Reproduce**
1. Install 'boto3-stubs (`pip install 'boto3-stubs[ec2]'`)
2. Try to type anything in Pycharm afterwards. (no background processes are running).

**Additional context**
OS X, `boto3-stubs`

**Comment by vemel** [comment]
Yes, PyCharm for some reason consumes a lot of RAM while parsing overloaded functions with Literal params. Unfortunetely, this is the only way to annotate `boto3.client` and `boto3.resourse`. To make it faster, use explicit type annotations:

```python
import boto3
from mypy_boto3.ec2 import EC2Client, EC2SerivceResource

ec2_client = boto3.client("ec2") # this one is slow
ec2_client_typed: EC2Client = boto3.client("ec2") # way faster due to explicit typing
ec2_resource: EC2SerivceResource = boto3.resource("ec2")
```

**Comment by mWozDev** [comment]
Thanks @vemel! I tried the solution you listed which caused a small increase in performance, but Pycharm is sadly still unusable as any typed changes cause major keyboard lag.

Would be more than happy to try any other solutions available 😄

**Comment by vemel** [comment]
Sorry for the delay. I installed PyCharm Community and I think I know how to rewrite boto3.client/resource annotations to make it faster.

**Comment by vemel** [comment]
In `boto3_stubs>=1.13.25.0` dynamic type annotations are no longer required, so I am closing this issue as it is outdated.
