### ISSUE TITLE
[BUG] Item "bytes" of "Union[bytes, IO[Any]]" has no attribute "read"

### ISSUE THREAD

**Issue by maxcountryman** [vemel/mypy_boto3_builder#19]
It seems that the return type of `obj.get()["Body"]` doesn't allow the caller to invoke the `read` method, instead causing mypy to complain with: `Item "bytes" of "Union[bytes, IO[Any]]" has no attribute "read"`.

A simple example to demonstrate this behavior:

```python
import boto3

from mypy_boto3_s3 import S3ServiceResource
from mypy_boto3_s3.service_resource import Object


class S3Client:

    def get_key(self, key: str, bucket_name: str) -> Object:
        res: S3ServiceResource = boto3.resource("s3", aws_access_key_id="...", aws_secret_access_key="...")
        obj: Object = res.Bucket(name=bucket_name).Object(key=key)
        obj.load()
        return obj

    def read_key(self, bucket_name: str, key: str) -> str:
        obj = self.get_key(key, bucket_name)
        body = obj.get()["Body"]
        return body.read().decode("utf-8")
```

I'm unsure if this is intended and if so how I would go about calling the `read` method?

**Comment by vemel** [comment]
This is because body can be both `bytes` and a byte stream. I do not know if there is a nicer way of doing this other than explicitly cast it to `IO[Any]`.

```python
from typing import cast, IO

    def read_key(self, bucket_name: str, key: str) -> str:
        obj = self.get_key(key, bucket_name)
        body = cast(IO[bytes], obj.get()["Body"])
        return body.read().decode("utf-8")
```

**Comment by maxcountryman** [comment]
> This is because body can be both `bytes` and a byte stream. I do not know if there is a nicer way of doing this other than explicitly cast it to `IO[Any]`.
> 
> ```python
> from typing import cast, IO
> 
>     def read_key(self, bucket_name: str, key: str) -> str:
>         obj = self.get_key(key, bucket_name)
>         body = cast(IO[bytes], obj.get()["Body"])
>         return body.read().decode("utf-8")
> ```

Thanks, this is cleaner than branching, which is what I was doing before.

**Comment by vemel** [comment]
Still, I think I need to change return type from `Union[bytes, IO[Any]]` to `Union[bytes, IO[bytes]]`

**Comment by geekingfrog** [comment]
Can the body really be `bytes` or a byte stream? From the doc for `S3.client.get_object`, the body is always a `StreamingBody`. From what I could see from the code, it's always a streamingBody, and never simply `bytes`. Same for the resource `Object.get`

**Comment by geekingfrog** [comment]
@vemel I have some changes nearly ready to go which look at the shape to check if there is a `streaming` property. When it's set to `True`, then the output type is `IO[bytes]`, otherwise it would simply be `bytes`. If that sounds alright to you, I can do a PR shortly.

**Comment by vemel** [comment]
Hi @geekingfrog ! Sorry for late response. If you have time, please submit a PR.

**Comment by vemel** [comment]
I just added a fix, so all `bytes or seekable file-like object` values are annotated as `Union[bytes, IO[bytes]]`. Would that work for you, guys?
