### ISSUE TITLE
Add support for installing all services

### ISSUE THREAD

**Issue by ilanbiala** [vemel/mypy_boto3_builder#24]
It would be nice to install for all services with something like:
```bash
python -m pip install 'boto3-stubs[all]'
```
like there is for essential:
```
```bash
python -m pip install 'boto3-stubs[essential]'
```

**Comment by vemel** [comment]
There was a way to do this before. Unfortunately, if you install all packages, generated `boto3/index.pyi` file is extremely big and PyCharm type suggestions just stop working. I believe you need around 200 GB of RAM to make it work in PyCharm. mypy also slows down a bit, but works as it should. I can re-add `all` extra.

Why do you need all packages?

**Comment by vemel** [comment]
Added to the latest release. Let me know if it works for you.

**Comment by ilanbiala** [comment]
For `mypy` to avoid having to keep adding packages to a Docker image whenever someone wants to use another part of `boto3`. Thanks!
