### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'mypy_boto3'

### ISSUE THREAD

**Issue by nh13** [vemel/mypy_boto3_builder#27]
First I create a python 3.8 conda environment and install [`pyfgaws`](https://github.com/fulcrumgenomics/pyfgaws):
```bash
❯ conda create -y -n debug-py38 python=3.8
❯ conda activate debug-py38
❯ python -m pip install pyfgaws
```

Next I trie to import the stub for batch:
```bash
❯ python
>>> import mypy_boto3.batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mypy_boto3'
```

So RTFM:
> However, if you use any other way or notice that services stubs do not work, you can build services index manually.
> ```python
> # Use this command when you add or remove service packages
> python -m mypy_boto3
> ```

That works:
```bash
❯ python -m mypy_boto3
mypy_boto3: INFO     Discovered Batch service stubs in mypy-boto3-batch
mypy_boto3: INFO     Discovered CloudWatchLogs service stubs in mypy-boto3-logs
mypy_boto3: INFO     You can now use Batch and CloudWatchLogs type annotations.
❯ python
>>> import mypy_boto3.batch
>>> 
```

But the manual also says:

> This package generates a few source files depending on services that you installed. Generation is done by a post-install script, so as long as you use pip, pipfile or poetry everything should be done automatically.

I am using `pip` to install the package ([`pyfgaws`](https://github.com/fulcrumgenomics/pyfgaws)), and that package is built using poetry with the [correct extras specified](https://github.com/fulcrumgenomics/pyfgaws/blob/master/pyproject.toml#L34). So why do I need to manually index, and/or why isn't the "post-install script" handling this for me automatically.

Thank-you in advance for any help you could offer.

**Comment by vemel** [comment]
Hello! Looks like index auto-generation does not work because packages are installed in a different order. It will only work if `mypy-boto3` is installed before `mypy-boto3-batch`

I am planning to remove auto-generation, because post-install way is hacky and does not allow me to use wheels. So it is always a good idea to run `python -m mypy_boto3` to generate index.

Let me know if you have any suggestions on how to make installation process easier. Thank you.

**Comment by vemel** [comment]
Hello. I am going to release builder v2, and main idea is to make `mypy_boto3` package and dynamic type annotations completely optional. Some changeswere already done in the latest release, so you can start using this package in a recommended way for v2:

```python
# client and resource annotations
from mypy_boto3_batch import BatchClient, BatchServiceResource 

# waiters and paginaators
from mypy_boto3_batch.waiter as batch_waiters
from mypy_boto3_batch.paginator as batch_paginators
```

Automatic generation is now required only if you want type discovery for `boto3.client` and `boto3.resource` functions. If you plan to provide explicit annotations for these functions, you do not need `mypy_boto3`

Remember that only `mypy` supports `boto3.client/resource` generated annotations. PyCharm for some reason consumes too much RAM for those, and VSCode does not support them at all.

**Comment by vemel** [comment]
Closing this issue as it is outdated due to v 2 release. Please update to `boto3_stubs>=1.13.25.0`. Thank you for the report!
