### ISSUE TITLE
better integration with visual studio code (without using explicit)

### ISSUE THREAD

**Issue by tekdj7** [vemel/mypy_boto3_builder#35]
look into better visual studio code integration, without requiring explicit type hinting. Maybe now with pylance extension, where stubs can be stored in a directory, and used from there, maybe that will help. so we don't have to add type hints to get auto-complete/hover working. See here: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Comment by vemel** [comment]
Thank you for the great idea! Yes, this is better than explicit type annotations for sure.

**Comment by vemel** [comment]
I am looking into integration with `pylance`/`pyright`. Should be doable and looks like Microsoft works a lot to make it standard https://github.com/microsoft/pylance-release

**Comment by vemel** [comment]
Finally, this is done! VSCode + Pylance should work without explicit type annotations starting from `1.14.54.1`. Please let me know if it works as it should for you.

**Comment by the-vampiire** [comment]
hey @vemel thank you for the awesome lib man. real game changer when working with boto.

i am using it in vscode and was wondering if there was a way to filter the suggestions? if i just open the brackets it shows a list of choices but if i type anything they disappear. maybe there is a setting for this you know about?

> on opening the brackets (list appears)

![image](https://user-images.githubusercontent.com/25523682/99890781-92e92900-2c28-11eb-99db-20a1ffd3b7a8.png)

> on typing anything to filter the list (it disappears)

![image](https://user-images.githubusercontent.com/25523682/99890810-ae543400-2c28-11eb-9e0c-5b8e36eb9bfa.png)

> same (with quotes)

![image](https://user-images.githubusercontent.com/25523682/99890813-b6ac6f00-2c28-11eb-9883-6269241b1911.png)
