### ISSUE TITLE
pyright: Stub file not found for "mypy_boto3_dynamodb" (reportMissingTypeStubs)

### ISSUE THREAD

**Issue by tekumara** [vemel/mypy_boto3_builder#36]
**To Reproduce**
1. Install 'boto3-stubs[dynamodb]'
2.  Run pyright on the following code sample

```python
import boto3
import mypy_boto3_dynamodb as dynamodb

client: dynamodb.DynamoDBClient = boto3.client("dynamodb")
```

3. Actual pyright output

```
  2:8 - error: Stub file not found for "mypy_boto3_dynamodb" (reportMissingTypeStubs)
  4:9 - error: Type of "DynamoDBClient" is unknown (reportUnknownMemberType)
  4:41 - error: "client" is not a known member of module (reportGeneralTypeIssues)
  4:35 - error: Type of "client" is unknown (reportUnknownMemberType)
  4:1 - error: Type of "client" is unknown (reportUnknownVariableType)
```

**Comment by tekumara** [comment]
Fixed by running `pyright --lib` which uses type annotations from `.py` files, when stubs are not available (see [import-resolution.md](https://github.com/microsoft/pyright/blob/5e4cbeca63cd8c56e930921247edece0c0e8e8c5/docs/import-resolution.md)).

**Comment by tekumara** [comment]
To fix` 4:35 - error: Expression of type "BaseClient" cannot be assigned to declared type "DynamoDBClient"`  run `python -m mypy_boto3dynamodb`.

Now I'm just left with `Stub file not found`

**Comment by vemel** [comment]
Thank you for the report. I have never used `pyright`, but I will take a look.

**Comment by tekumara** [comment]
Thanks @vemel! 

So I can generate the type stubs with pyright like this:
```
pyright --createstub mypy_boto3_dynamodb
```
Which fixes the `Stub file not found` error. 

But maybe the stubs could be shipped with `boto3-stubs` somehow?

**Comment by vemel** [comment]
Unfortunately, this means adding all 200+ services to boto3_stubs and it takes more than 15 MB of space. Probably I can somehow let pyright know that `mypy_boto3_dynamodb` is a stub package, so it adds it automatically on import?

I tried `pyright`, works really well, so I will definitely invest some time into supporting it.

Your solution should be added to docs, or maybe I can do it in command

```bash
mypy_boto3
```

if `pyright` is installed.

**Comment by tekumara** [comment]
Generating the `.pyi` stubs when running `mypy_boto3` sounds like a good solution!

In the meantime, I've discovered a workaround. The `Stub file not found .. (reportMissingTypeStubs)` error only occurs when running pyright in strict mode. It's possible to turn this error off in pyright by switching to basic mode (which I'd rather not do) or by selectively disabling the `reportMissingTypeStubs` error. One way to do that is to add the following to my source file:
```
# pyright: reportMissingTypeStubs=false
```

See https://github.com/microsoft/pyright/issues/601 for more details.

**Comment by vemel** [comment]
I added initial support for `pyright` to `boto3_stubs>=1.14.51.1`. See release notes for more details and future plans.

**Comment by tekumara** [comment]
Thanks @vemel ! I'm a big fan of pyright so super pleased there's interest in making the boto stubs compatible! I had a look but couldn't find the relevant release notes, could you send me the link?

I've also tried 1.14.51.2 and it seem to be returning type `BaseClient` for  `boto3.client("ec2")` rather than `EC2Client`.

To date I've been using [this script](https://github.com/seek-oss/aec/blob/master/.install-typings-boto3.sh) to generate stubs for pyright. This seems to work well and gives accurate types, eg: `EC2Client` as well as providing all the typed dictionaries etc. 

It basically runs mypy_boto3 and then copies all the `.py` as `.pyi` files into the `typings/` directory ie: default `stubPath` for pyright (see [Pyright configuation](https://github.com/microsoft/pyright/blob/7808935fa7d02278fa04744fbc9fda2fc5e2189e/docs/configuration.md)).

This is what it looks like for [my project](https://github.com/seek-oss/aec), which uses `boto3-stubs[ec2,sqs,compute-optimizer,ssm]==1.14.52.1`:
```
typings/
├── boto3
│   └── __init__.pyi
├── mypy_boto3
│   ├── compute_optimizer
│   │   ├── __init__.pyi
│   │   ├── client.pyi
│   │   └── type_defs.pyi
│   ├── ec2
│   │   ├── __init__.pyi
│   │   ├── client.pyi
│   │   ├── paginator.pyi
│   │   ├── service_resource.pyi
│   │   ├── type_defs.pyi
│   │   └── waiter.pyi
│   ├── sqs
│   │   ├── __init__.pyi
│   │   ├── client.pyi
│   │   ├── paginator.pyi
│   │   ├── service_resource.pyi
│   │   └── type_defs.pyi
│   └── ssm
│       ├── __init__.pyi
│       ├── client.pyi
│       ├── paginator.pyi
│       ├── type_defs.pyi
│       └── waiter.pyi
├── mypy_boto3_compute_optimizer
│   ├── __init__.pyi
│   ├── client.pyi
│   └── type_defs.pyi
├── mypy_boto3_ec2
│   ├── __init__.pyi
│   ├── client.pyi
│   ├── paginator.pyi
│   ├── service_resource.pyi
│   ├── type_defs.pyi
│   └── waiter.pyi
├── mypy_boto3_sqs
│   ├── __init__.pyi
│   ├── client.pyi
│   ├── paginator.pyi
│   ├── service_resource.pyi
│   └── type_defs.pyi
└── mypy_boto3_ssm
    ├── __init__.pyi
    ├── client.pyi
    ├── paginator.pyi
    ├── type_defs.pyi
    └── waiter.pyi

10 directories, 39 files
```

**Comment by vemel** [comment]
@tekumara this is awesome! I completely forgot about `typings` folder. Actually, I believe you can do something like

```bash
pip install --install-option="--prefix=`cwd`/typings" --ignore-installed 'boto3-stubs[ec2,sqs,compute-optimizer,ssm]'
```

and then do renaming.

I will cross-check if everything works correctly with `*.pyi` files instead of `*.py` (I think, imports for mypy will be broken), and release a new version.

So, the plan is:
- rename everything to `pyi`
- fix mypy imports
- cross-check that installation to `typings` works as it should
- use pre-generated client/resource overloads for all services. there are 238 overload variants, so let's hope that `pyright` can handle it, because both `mypy` and `PyCharm` fail

**Comment by tekumara** [comment]
Oh wow, I didn't know you could do a pip install like that! 😲 

FYI: there's the odd place I have to use an explicit type annotation to make pyright happy, eg:

```python
from mypy_boto3_ec2.type_defs import FilterTypeDef
....
filters: List[FilterTypeDef] = [] if name is None else [{"Name": "tag:Name", "Values": [name]}]
```
(see [ec2.py#L171](https://github.com/seek-oss/aec/blob/8626144040ff0e28ae7a498b860b20faea2562a4/aec/command/ec2.py#L171))

So I need the stubs installed as a runtime application dependency, as well as installing them into `typings/`

**Comment by vemel** [comment]
Okay, progress so far: https://github.com/vemel/mypy_boto3_builder/pull/47

Also, implicit type annotations should be fully supported now: https://github.com/vemel/mypy_boto3_builder/pull/47/files#diff-eeb707bbf2c07f3a17387150bca7901f

Regarding `List[FilterTypeDef]` -  I believe this is the only correct solution in this case.

**Comment by vemel** [comment]
Please try a new version `1.14.54.1`. Explicit type annotations are no longer required, check new example: https://github.com/vemel/mypy_boto3_builder/blob/master/examples/dynamodb_example.py

Let me know if it works as expected.

**Comment by tekumara** [comment]
Using version 1.14.54.1 on [my project](https://github.com/seek-oss/aec) I'm getting the import warnings from pyright/pylint:
```
/Users/tekumara/code/aec/aec/command/compute_optimizer.py
  7:6 - warning: Import "mypy_boto3_compute_optimizer.type_defs" could not be resolved from source (reportMissingModuleSource)
/Users/tekumara/code/aec/aec/command/ec2.py
  6:6 - warning: Import "mypy_boto3_ec2.type_defs" could not be resolved from source (reportMissingModuleSource)
/Users/tekumara/code/aec/aec/command/sqs.py
  8:6 - warning: Import "mypy_boto3_sqs.client" could not be resolved from source (reportMissingModuleSource)
  9:6 - warning: Import "mypy_boto3_sqs.type_defs" could not be resolved from source (reportMissingModuleSource)
0 errors, 4 warnings 
Completed in 2.828sec
```

pyright now takes 2.8 sec (previously it was 1.8 sec).

PyCharm 2020.2 is still using >700% CPU. PyCharm also makes no inference for ec2_client (previously this was `BaseClient`):
```
    ec2_client = boto3.client("ec2")
```

Overall, I think the previous version is better for me (ie: version 1.14.52.1 with mypy_boto3) .

**Comment by vemel** [comment]
@tekumara The newest version should not have this issue. I added `py` files the same as `pyi` files to every service package, so imports should work.

**Comment by tekumara** [comment]
Thank @vemel I can confirm the above warnings have gone away when I use 1.14.60.0.

I noticed `session.pyi` contains all the generated `client` and `resource` overloads too, just curious why that is?

**Comment by vemel** [comment]
Because you can create client/resource two ways

```python
import boto3
from boto3.session import Session

# this will generate a default session for you
# before creating a client
client = boto3.client('s3')

# create a session first to share it across clients
# or override region or access keys
session = Session(...)
client = session.client('s3')
```
