### ISSUE TITLE
pyright error: "resource" is not a known member of module

### ISSUE THREAD

**Issue by tekumara** [vemel/mypy_boto3_builder#39]
Setup to reproduce the behavior:
```
pip install 'boto3-stubs[s3]==1.14.30'
pip install 'boto3==1.14.30'
python -m mypy_boto3
```

Run pyright on the following code sample:

```python
import boto3

s3_resource = boto3.resource('s3', region_name='us-east-1')
```

pyright output:
```
No configuration file found.
stubPath /private/tmp/t/typings is not a valid directory.
Assuming Python platform Darwin
Searching for source files
Found 1 source file
/private/tmp/t/test.py
  3:21 - error: "resource" is not a known member of module (reportGeneralTypeIssues)
1 error, 0 warnings
Completed in 0.576sec
```

**Expected output**

No type errors. 

NB: When only `boto3` is installed (ie: without stubs) there are no type errors.

pyright 1.1.58

**Comment by tekumara** [comment]
I raised this here https://github.com/microsoft/pyright/issues/891. It appears to be caused by the boto3 stub file (init.pyi) importing symbols from an implementation file (boto3_init.py).

**Comment by tekumara** [comment]
A workaround is to use `boto3_init_gen.py` as a boto3 stub:
```
mkdir -p typings/boto3
cp "$VIRTUAL_ENV"/lib/python*/site-packages/mypy_boto3/boto3_init_gen.py typings/boto3/__init__.pyi
```
This will make pyright happy.

**Comment by vemel** [comment]
I just switched to `pyright`, so I hope to get a fully-compatible version during this week. This is very good idea to generate `pyi` files instead of `py`. I will give it a try.

**Comment by vemel** [comment]
I have just released initial support for `pyright`. See release notes for details. Please let me know if you have any suggestions for `pyright` support improvement.
