### ISSUE TITLE
[BUG] EC2.Volume.create_tags expects Resources

### ISSUE THREAD

**Issue by tekumara** [vemel/mypy_boto3_builder#42]
The type stub generated for `Volume.create_tags` (in *service_resource.py*), expects a `Resources` argument:
```
class Volume(Boto3ServiceResource):

...

    def create_tags(
        self, Resources: List[Any], Tags: List[TagTypeDef], DryRun: bool = None
    ) -> _Tag:
        """
        [Volume.create_tags documentation](https://boto3.amazonaws.com/v1/documentation/api/1.14.46/reference/services/ec2.html#EC2.Volume.create_tags)
        """
```

However, [EC2.Volume.create_tags](https://boto3.amazonaws.com/v1/documentation/api/1.14.46/reference/services/ec2.html#EC2.Volume.create_tags) doesn't require the `Resources` argument.

boto3-stubs 1.14.46.0

**Comment by vemel** [comment]
Same as https://github.com/vemel/mypy_boto3_builder/issues/44. I will leave it open

**Comment by vemel** [comment]
Hello!

This was fixed in boto3_stubs>=1.14.51.1. Let me know if the issue still exists.

**Comment by takeda** [comment]
@vemel I'm still seeing the issue with `EC2.Image.create_tags()` on `1.14.51.1`

**Comment by vemel** [comment]
@takeda please check `1.14.52.1`. Quick fix did not work, I had to stub all resources in `EC2`. Actually, that was a good fix, `ec2.Instance.create_tags` and `ec2.Instalce.delete_tags` were completely incorrect.

I have a feeling that it has been changed in `boto3 1.14.*`, but I did not check.
