### ISSUE TITLE
[BUG] EC2.Image.create_tags() expects Resources

### ISSUE THREAD

**Issue by takeda** [vemel/mypy_boto3_builder#44]
**Describe the bug**
Probably related to #42, looks like the signature used for Image.create_tags() is from the client, and not from the image resource.
```python
    ec2: EC2ServiceResource = boto3.resource("ec2")
    image = ec2.Image(ami)
    image.create_tags(Tags=tags)
```
version: 1.14.49.0

**Comment by vemel** [comment]
Hmm, I used a hardcode to set all `Tags` arguments for `ec2` to `List[EC2Tag]`, because `boto3` modifies `create_tags` and `delete_tags`, so annotations for these functions cannot be builld for botocore schemas. I solution could be to leave hardcode only for client, but not for resource.

**Comment by vemel** [comment]
Similar to https://github.com/vemel/mypy_boto3_builder/issues/45
