### ISSUE TITLE
[BUG] EC2 tags are described as List[TagTypeDef] should be Optional[List[TagTypeDef]]

### ISSUE THREAD

**Issue by takeda** [vemel/mypy_boto3_builder#46]
**Describe the bug**
In EC2 (and probably other components) tags are described as List[TagTypeDef], the boto3 can also return null (None), when there are no tags, this causes mypy to not detect bugs of not checking to it.

To make things easier for developers, it would be great to provide a single type for that list, so there's less typing and also can be easily changed if the type changes, for example:

```python
TagsTypeDef = Optional[List[TagTypeDef]]
```

version: 1.14.51.0

**Comment by vemel** [comment]
Hi!

Thank you for the report. You have a valid point, however I do not wrap annotations in `Optional` for reason. Passing None is not always the same as not passing the argument, and botocore schemas do not describe in None value is valid. I did not find a proper way to check if None value can be passed safely for an optional arg, only trial and error.

General solution would be: always wrap optional arg annotation in `Optional` and have a black list for cases when it is not working.

**Comment by vemel** [comment]
Hello!

This was fixed in `boto3_stubs>=1.14.51.1`. Let me know if the issue still exists.
