### ISSUE TITLE
[BUG] mypy-boto3-redshift-data no matching distribution error

### ISSUE THREAD

**Issue by OskergMonReap** [vemel/mypy_boto3_builder#49]
**Describe the bug**
Starting today, attempting to upgrade via `pip install --user --upgrade boto3-stubs[all]` fails due to the `mypy-boto3-redshift-data` package

**To Reproduce**
`pip install --user --upgrade boto3-stubs[all]`

**Output:**
```
ERROR: Could not find a version that satisfies the requirement mypy-boto3-redshift-data==1.14.58.0; extra == "all" (from boto3-stubs[all]) (from versions: none)
ERROR: No matching distribution found for mypy-boto3-redshift-data==1.14.58.0; extra == "all" (from boto3-stubs[all])
```
**Expected output**
successful installation of upgraded packages

**Additional context**
OS: Arch Linux / Ubuntu / Opensuse
Install Method: pip

Arch Linux is my daily driver OS where I first noticed, as a test I attempted on a few other machines (both of which were fresh installs, ie `pip install --user boto3-stubs[all]`) and they failed with same errors

**Comment by vemel** [comment]
Thank you for your report. It was an experiment to generate type annotations for services that are not explicitly added. Generation worked as it should, but these packages were not uploaded to PyPI.

It was fixed in the latest version, please update `boto3-stubs`.

**Comment by vemel** [comment]
Just cross-checked. `pip install boto3-stubs[all]` works.
