### ISSUE TITLE
Using remote PyCharm docker compose and building annotations

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [vemel/mypy_boto3_builder#50]
**Describe the bug**

I'm using Docker-compose and my Python interpreter is using my compose file.

Takes forever for PyCharm to update its screen with the type annotations. For example, filling in parameters still shows that I'm missing the exact same parameter I just filled in.

Note I didn't build the type annotations and put it into an output file. I don't know how using my current configuration:

**To Reproduce**

Create a sample project with boto3 and use Docker compose to run the program (using a Dockerfile running Python 3.8).

Go to settings, Python Interpreter, and add an interpreter. Choose docker-compose. Select your compose file, then select the service. PyCharm should now be indexing your installed requirements.

**The problem is I feel like I need to somehow build the type annotations. Not sure how I would do that**. But here's what I got:

A sample file:

```python
import boto3
from botocore.exceptions import ClientError
from mypy_boto3_s3.client import S3Client 


def generate_presigned_url(key: str) -> str:
    client: S3Client = boto3.client("s3")
    try:
        response = client.generate_presigned_url(
            "get_object",
            Params={"Bucket": "bucket name", "Key": key},
            ExpiresIn=expires,
        )
    except ClientError as e:
        return None

    return response
```

**Additional context**

IDE: PyCharm 2020.2.1

OS: MacOS

After writing this issue, removing the stubs import, and removing the type hints, after opening the file back up after closing it, PyCharm is overheating my laptop and still shows the same errors.

**Comment by vemel** [comment]
This is because PyCharm for some reason consumes too much memory for `Literal` overloads, and `boto3-stubs` has 230+ overloads like these for `boto3.client/resource` to find a correct service. The solution in your case would be to remove `boto3-stubs` package and use `mypy-boto3-s3` (or any other service packages) directly. You will not have automatic type discovery, but since you are using explicit type annotations, this should work for you.

```bash
pip uninstall boto3-stubs mypy_boto3
pip install mypy-boto3-s3
```

Please let me know if it works for you.

**Comment by Andrew-Chen-Wang** [comment]
Hey @vemel Thanks for the quick response. I saw the "response needed" tag so I wanted to keep you updated (so that I don't leave you in the dark) as I'm currently having to reinstall the packages because... yippee PyCharm remote docker interpreter.

Could you clarify the difference between boto3-stubs and mypy-boto3-s3? I just find it confusing since I have boto3-stubs[s3] in my requirements file, so the amount of literals shouldn't be a problem.

**Comment by vemel** [comment]
`boto3-stubs` contains type annotations for `boto3` package and also overloads for `boto3.client/resource`, so you do not need explicit type annotations 

```python
# explicit type annotation
client: S3Client = boto3.client("s3")

# implicit type discovery with `boto3-stubs[s3]`
# works the same as the line above
client = boto3.client("s3")
```

Unfortunately, this works extremely slow in PyCharm. I am not sure if they have a bug report for it.

`mypy-boto3-s3` package contains only annotations for # client/resource, so you always need to annotate your code for a proper type checking and auto-complete:

```python
from mypy_boto3_s3.client import S3Client

# explicit type annotation
client: S3Client = boto3.client("s3")
```

So, I suggest to uninstall `boto3-stubs` package, so PyCharm does not try to discover types and rely on your type annotations. Let me know how it works, I do not use PyCharm.

**Comment by Andrew-Chen-Wang** [comment]
Just finished indexing the package. PyCharm is running more smoothly and not overheating. It's still a little slow, but I saw another GH issue mentioning the two second ish delay which does still happen in my files. But in my opinion, the problem's resolved by only installing `mypy_boto3_s3`.

I think this could be made clearer in the README. In the PyCharm section, you could state (in a second sentence) to only install the `mypy_boto3_SERVICE` package. Again thanks for the quick response and awesome package!

**Comment by Andrew-Chen-Wang** [comment]
I can't find an issue regarding overloading the Literal in the JetBrains bug tracker. The reason may be because PyCharm is saving these typings inside an XML file, but I'm not sure.
