### ISSUE TITLE
[Request] types for lambda handler parameters

### ISSUE THREAD

**Issue by reegnz** [vemel/mypy_boto3_builder#53]
**Describe the bug**
When writing a lambda handler function, I would like to have type annotations for the input parameter types (event and context).

**Additional context**
This might not be part of boto3, so that could be the reason for not being able to find it.
I would welcome suggestions as well, not necessarily implementation of it.

**Comment by vemel** [comment]
Hi @reegnz 

Yes, AWS Lambda typing is not a part of `boto3`, so this feature is out of scope of `boto3-stubs` project.
However, you can use smth like this: https://github.com/illagrenan/lambda-typing/blob/master/lambda_typing/types.py

Let me know if this helps.
