### ISSUE TITLE
pycharm uses 100 percent cpu with latest boto3-stubs package

### ISSUE THREAD

**Issue by Ranjith072** [vemel/mypy_boto3_builder#54]
**Describe the bug**
i am using boto3-stubs(1.16.9.0) on Pycharm as soon as i install this package and try to use some shortcuts on pycharm does not respond ,when i check the task manager i see cpu being utilized 100 by the pycharm .
if i uninstall the boto3-stubs everything  works well .i was earlier using the 1.13.19.0 for boto3 and its stubs and everything working quite well until  my renovate updated it to latest version.

**To Reproduce**
1. Install 'boto3-stubs[...]'
import boto3 
try to create any client and try for auto completion then it will run forever to get the backend reference.

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.
windows 10
pip install boto3-stubs[cloudfront,dynamodb,kms,lambda,ses,sqs,s3,ssm,secretsmanager,glue,ses,sns,stepfunctions,redshift,cognito,apigateway,athena,ec2,batch]==1.16.9.0

**Comment by vemel** [comment]
Thank you for your report.

This is a known issue. For some reason PyCharm type checker consumes too much memory for function overloads with `Literal`, and `boto3-stubs` uses it for `boto3.client(...)` and `boto3.resource(...)` calls.


`mypy` and `pyright` do not have this issue, so one option would be to disable PyCharm built-in type checker and use an external one.

Or you can try to use explicit type annotations, so PyCharm does not need to discover types automatically, this should help as well:

```python
import boto3 
from mypy_boto3_s3.client import S3Client

s3_client = boto3.client("s3") # slow autocomplete
s3_client: S3Client = boto3.client("s3") # fast auto complete, because you specified type explicitly
```

Please let me know what works best for you. I am still trying to find the best solution that covers all type checkers.

**Comment by Ranjith072** [comment]
but this was working totally fine few weeks before with the boto3-stubs v1.13.19.0 .

**Comment by vemel** [comment]
There was no builder changes that could affect performance. Probably you installed more subservice packages, this is why you got this issue.

**Comment by vemel** [comment]
Sorry, I did not see that you updated from `1.13.x` to `1.16.x`. Yes, this is because I got rid of auto-generated packages. As I said, add annotations explicitly and try to remove `boto3-stubs` master package, so PyCharm does not try to resolve `Literal` overloads.

**Comment by vemel** [comment]
Please keep me updated if you resolve the issue. We can add it to documentation.

**Comment by vemel** [comment]
Hello @Ranjith072 

I have just released builder 4.0.0. It has a workaround that reduces CPU usage for PyCharm while they are fixing Literal resolution: https://github.com/vemel/mypy_boto3_builder#pycharm-consumes-too-much-cpu

Please try:

```bash
pip install mypy_boto3_builder
python -m mypy_boto3_builder --installed --skip-services typings -s cloudfront dynamodb kms lambda ses sqs s3 ssm secretsmanager glue ses sns stepfunctions redshift cognito apigateway athena ec2 batch
```

Add `<project_root>/typings` folder to your [Interpreter Paths](https://www.jetbrains.com/help/pycharm/stubs.html#reuse-stubs)

If CPU usage is still high, try to reduce number of services in overloads and use explicit type annotations for the rest.

```bash
python -m mypy_boto3_builder --installed --skip-services typings -s s3 ses ec2 sns
```

Let me know if this works for you.

**Comment by Ranjith072** [comment]
Hi @vemel i have started to use explicit type annotations and its working out well for me .thanks for the notifying me :)

**Comment by vemel** [comment]
I strongly recommend to try generating your own boto3-stubs in `typings` dir as I wrote above. This way yo can avoid using explicit type annotations. I checked performance with all of your services installed on my machine, works pretty fast and auto-complete is working as it should.
