### ISSUE TITLE
Is autocomplete through pyright supported?

### ISSUE THREAD

**Issue by rirze** [vemel/mypy_boto3_builder#59]
I'm having a hard time understanding if autocompelete of boto3 clients is supported by this library-- is this possible or am I misunderstanding something? Narrowing the question further, is autocomplete through pyright supported?

My current use case is using Emacs with a pyright server. After setting it up, I'm getting type and return object key/attribute checking, which has been wonderful. But I'm not getting any autocomplete for boto3 clients:
```python3
ec2 = boto3.client('ec2')
ec2.
### ^[autocomplete should come up here]
```

Is there anything I can configure to enable this feature? Thanks.

**Comment by vemel** [comment]
I have never tried to use it directly with `pyright`, only with `Pylance` in VSCode. As far as I understand, Pylance is responsible for autocomplete.

I am going to check if it is possible to get autocomplete working with `pyright` itself.

**Comment by rirze** [comment]
Thanks for the detailed explanation and test case. Here's what I found:

Making sure, I verified that I had `boto3-stubs[all]` and `mypy-boto3-*` installed for all services available. This is a bit overkill, but I had done this before filing this issue anyways. 

To clarify, for autocomplete on `boto3.client`, I'm expecting API calls to show up, not just `boto3.client` attributes and functions that are the same for every service. I wasn't clear about that, sorry. I'm getting these results showing up, but they're not useful for me:
![image](https://user-images.githubusercontent.com/3255334/101654130-28006600-3a0e-11eb-9a33-bc5471a4e84b.png)
I would very much like to have API calls show up instead. 

I suspect your example also showcases this. When I hover at `my_int.`, my autocomplete gives me attributes for `datetime`. I suspect it's not narrowing down results based on overload but rather taking the `Union[datetime, int]` quite naively. 

Would love to hear your thoughts.

**Comment by vemel** [comment]
Looks like you are getting only attributes and functions from `BaseClient`, not from `EC2Client`. For some reason `lsp-pyright` does not support overloads properly, even though `pyright` itself supports them. 

I do not know if is a misconfiguration in `lsp-pyright` or a real bug in `pyright`. I filed them an issue here: https://github.com/microsoft/pyright/issues/1256

**Comment by vemel** [comment]
I am very new to emacs, could you please share your init file, or an init file for auto-complete, lsp-pyright and `.venv` usage?

**Comment by rirze** [comment]
@vemel It might be a burden to share my entire init.el file, so I'll work on creating a specific setup where I can duplicate the issue on new fresh install. I'll share that over on the lsp-pyright bug tracker to see what they say.

**Comment by vemel** [comment]
Cool! I made is work, but looks like `lsp-pyright` package does nothing in my case. I followed this tutorial: https://gist.github.com/widdowquinn/987164746810f4e8b88402628b387d39

**Comment by rirze** [comment]
Ugh, I should've done this first. Using a barebones setup like this: 
https://gist.github.com/rirze/bf13fd7b92b8dc92224895cc6013476a

gives me the right autocomplete options. Now I have to do the hard task of combing through my setup to see what is going wrong. 

Sorry for the rabbit hole, but thanks for helping realize this.

**Comment by rirze** [comment]
Update: I feel even more dumb.

I had a `jedi` checker installed and I think that was causing problems. Removing that package now fixes autocomplete behavior.

**Comment by vemel** [comment]
Thank you for investigating it!

Could you please write a short guide how to add boto3 auto-complete and type checking to Emacs? I think, this can be added to readme

**Comment by rirze** [comment]
I'm not sure this would be the right place for it imo

[lsp-pyright](https://github.com/emacs-lsp/lsp-pyright) has a simple recipe for using `pyright` in Emacs and I only added an additional variable to make it work as expected when the `python` executable doesn't point to `python3`.  

If you think it could be helpful, then something like this could be added:

--------------

*Insert after `mypy_boto3_builder` steps*

Recommended prerequisites:
- [`use-package`](https://github.com/jwiegley/use-package) for package management. A further recommendation is to use [`straight.el`](https://github.com/raxod502/straight.el) but this is subjective on your setup. 
- [`company`](https://github.com/company-mode/company-mode) for autocompletion popup box. If you prefer a different UI, refer to [lsp docs](https://emacs-lsp.github.io/lsp-mode/page/installation/) 
- [`lsp`](https://github.com/emacs-lsp/lsp-mode/) for enabling language-server support. An alternative would be [`eglot`](https://github.com/joaotavora/eglot), but at this time, they do not support `pyright` out of the box.
- [`flycheck`](https://github.com/flycheck/flycheck) for integrating smarter syntax checkers (`flake8`, `pylint`, etc.). 

Then one can add this snippet to their config (adjusted from [lsp-pyright's README](https://github.com/emacs-lsp/lsp-pyright)):
```elisp
(use-package lsp-pyright
  :ensure t
  :hook (python-mode . (lambda ()
                          (require 'lsp-pyright)
                          (lsp)))  ; or lsp-deferred
  :init (when (executable-find "python3")
          (setq lsp-pyright-python-executable-cmd "python3"))
  )
```

A sample config could look like this: 
https://gist.github.com/rirze/bf13fd7b92b8dc92224895cc6013476a
