### ISSUE TITLE
Implicit type annotations not recognised with the new version in pycharm [BUG]

### ISSUE THREAD

**Issue by FaridNeshat-TomTom** [vemel/mypy_boto3_builder#60]
After following the instructions with the project new version, the boto3 client type annotations are not recognised, and rather each boto3 client type according to PyCharm is BaseClient, which doesn't contain the client specific methods.

I think this is caused by the fact that output direct of mypy_boto3_builder is not a format compatible with python's import system. After running `python -m mypy_boto3_builder typings -s s3`, I'd get the following directory structure:

```
typings
├── boto3_stubs_package
│   ├── README.md
│   ├── boto3-stubs
│   └── setup.py
├── master_package
│   ├── README.md
│   ├── mypy_boto3
│   └── setup.py
└── mypy_boto3_s3_package
    ├── README.md
    ├── mypy_boto3_s3
    └── setup.py
```

The problem here PyCharm is looking for package ending with `-stubs` but it only sees, `boto3_stubs_package`, `master_package` and `mypy_boto3_s3_package`. boto3-stubs also requires `mypy_boto3_s3` but again python interpreter doesn't see it. If we move out the directories to one level higher then everything starts working. So this is what I what did:

```
typings
├── boto3-stubs
├── mypy_boto3
├── mypy_boto3_s3
```

Of course this is just one way to solve the problem.

**To Reproduce**
1. Run the following commands:
```
pip install mypy_boto3_builder boto3
python -m mypy_boto3_builder typings -s s3
```
2. In pycharm add the typings directory to the libraries path.

3.  Open the following code sample in pycharm:

```python
import boto3

s3 = boto3.client('s3')
...
```
4. Check the type of s3

** actual type**
```
BaseClient
```

**Expected type**
```
S3Client
```

**Additional context**
MacOS v10.15.7
mypy-boto3-builder==4.3.1
boto3==1.16.43
PyCharm Community 2020.2.5

**Comment by vemel** [comment]
I checked it with pycharm and I was sure that `-stubs` part is not needed. The fix should be trivial, so I am going to test again.

Thank you for your report!

**Comment by vemel** [comment]
OMG, I overlooked that you are trying to generate packages for installation, not for usage. You should provide `--installed` flag to generate already installed packages:


```bash
python -m mypy_boto3_builder --installed --skip-services -d -s s3
```

You can find more info here: https://github.com/vemel/mypy_boto3_builder#pycharm-consumes-too-much-cpu

Please keep in mind that you still need `boto3-stubs` package, but you can insall it directly from pypi:

```bash
python -m pip install `boto3-stubs`
```

**Comment by FaridNeshat-TomTom** [comment]
Hi @vemel,

Thanks a lot for taking the time and looking over this. Indeed that was the problem. I misunderstood `--installed` thinking that it would look at what boto3-stubs packages I have installed and it would generate types for those, which I didn't want. 

After running it with the `--installed` flag it works out of the box.

Cheers
