### ISSUE TITLE
stubs not working in Visual Studio Code, when passing boto client to a function

### ISSUE THREAD

**Issue by tekdj7** [vemel/mypy_boto3_builder#61]
Thanks for looking into this.

**THIS WORKS**:  As client is declared globally, auto-complete for `s3_client.`, and hover on `get_bucket_policy` shows stub info and boto3 URL for API call.

```python
s3_client = boto3.client("s3")

def get_bucket_policy(bucket):
    response = s3_client.get_bucket_policy(Bucket=bucket)
    return response

if __name__ == "__main__":
    bucket = "example-bucket"
    response = get_bucket_policy(bucket)
    print(f"{response=}")
```

**THIS DOES NOT WORK**:  As client is not declared globally, and instead passed to the function, auto-complete for `s3_client.`, and hover on `get_bucket_policy` shows `Unknown`

```python
def get_bucket_policy(s3_client, bucket):
    response = s3_client.get_bucket_policy(Bucket=bucket)
    return response

if __name__ == "__main__":
    s3_client = boto3.client("s3")
    bucket = "example-bucket"
    response = get_bucket_policy(s3_client, bucket)
    print(f"{response=}")
```

**Comment by vemel** [comment]
In this case, you have to use explicit type annotations

```python
from mypy_boto3_s3.client import S3Client

def get_bucket_policy(s3_client: S3Client, bucket: str):
    response = s3_client.get_bucket_policy(Bucket=bucket)
    return response
```

**Comment by tekdj7** [comment]
Any other options, that doesn't make `mypy_boto_s3.client` now a dependency for my script.  Other users running the script may not have `mypy`, and I don't want to make it a requirement for them.  

Also, doing the below block of code, reports `S3Client is possibly unbound - Pylance *reportUnboundVariable)` in my `get_bucket_policy` function.  What is the best way to resolve this?

```python
# explicit type-hint, when client not used globally & instead passed to a function
try:
    from mypy_boto3_s3.client import S3Client
except ModuleNotFoundError:
    pass

def get_bucket_policy(s3_client: S3Client, bucket: str):
    response = s3_client.get_bucket_policy(Bucket=bucket)
    return response
```

**Comment by ITProKyle** [comment]
```python
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mypy_boto3_s3.client import S3Client

def get_bucket_policy(s3_client: S3Client, bucket: str):
    response = s3_client.get_bucket_policy(Bucket=bucket)
    return response
```

This should resolve the issue and not require mypy/mypy_boto3_s3 as a runtime dependency. Note `from __future__ import annotations` requires python >= 3.7.

If you need to account for python <3.7; >3 you can omit `from __future__ import annotations` and wrap `S3Client` in quotes where it's used like below.

```python
def get_bucket_policy(s3_client: "S3Client", bucket: str):
```

**Comment by tekdj7** [comment]
@vemel @ITProKyle thanks for the help, the solutions solved my problem, and ensured `mypy` did not become a runtime dependency.
