### ISSUE TITLE
botocore stubs

### ISSUE THREAD

**Issue by tekdj7** [vemel/mypy_boto3_builder#62]
Any plans for botocore stubs? In the meanwhile, do you have have a workaround to get botocore stubs?

**Comment by vemel** [comment]
Yes, I definitely plan to stub botocore as well. However, it will be a separate static package. THis project is only for auto-generated stubs for boto3.

**Comment by tekdj7** [comment]
Sounds good. ETA on when you think you will have a botocore package ready?

**Comment by vemel** [comment]
I believe, in two or three weeks.

**Comment by sbdchd** [comment]
I created some basic stubs via [`stubgen`](https://mypy.readthedocs.io/en/stable/stubgen.html) for botocore available on pypi as `botocore-types`

repo: https://github.com/sbdchd/botocore-types

**Comment by vemel** [comment]
@sbdchd thank you a lot!

I have finally released `botocore-stubs`.Stubs are not complete yet, so please test them.

**Comment by vemel** [comment]
https://pypi.org/project/botocore-stubs/
