### ISSUE TITLE
share boto3-stubs across virtual environments

### ISSUE THREAD

**Issue by tekdj7** [vemel/mypy_boto3_builder#63]
Have a Mac running Visual Studio Code with Pylance. boto3-stubs works fine. Since there are like 256 packages (1 per service), is there any way that I can install this in a central location that I can then use it across all of my virtual environments for both overload annotations, and when explicit annotations are needed?  This way I don't have to install these packages on across so many virtual environments. And as I'm doing type-checking, and its not a run-time dependency, I don't want to keep installing 1 package at a time per service as I need them, hence I install all of them with boto3-stubs[*]

**Comment by vemel** [comment]
Hello,

You can use `pip install 'boto3-stubs[all]' --target=/my/dir` to install packages too `/my/dir`. I recommend to use `boto3-stubs[all]` instead of `boto3-stubs[*]`.

Also, instead of installation, you can generate ready for use packages with `mypy_boto3_builder`.

https://github.com/vemel/mypy_boto3_builder#locally

**Comment by tekdj7** [comment]
If I do either of these options, how do I do explicit annotations when needed, without getting import error, module not found. 

I have a scheduled job that checks for my outdated pip packages and then updates. 

If I go with pip install to directory, then pip list won't show, so will just have to update job to pip install to directory every time it runs, right?  

If I go with option 2, how does that differentiate from option 1? In my scenario, why should I use it over pip install to directory?

Wish I can do pipx install boto3-stubs[all], and then maybe get visual studio code and my environments to know how to use it for implicit annotations (overload) and explicit annotations (imports)

**Comment by vemel** [comment]
I have never used pipx, If you want to install/update packages using pip/pipx, install to `site-packages`, not locally.

On the other hand, do not add `boto3-stubs[*]` as a dependency, use it as a dev-dependency.

I hope this helps. Sorry for the late response.
