### ISSUE TITLE
Mark arguments that support passing None as optional

### ISSUE THREAD

**Issue by arnimarj** [vemel/mypy_boto3_builder#64]
**Describe the bug**

It seems that the annotations for `STSClient.assume_role` are wrong:

```python
    def assume_role(
        self,
        RoleArn: str,
        RoleSessionName: str,
        PolicyArns: List[PolicyDescriptorTypeTypeDef] = None,
        Policy: str = None,
        DurationSeconds: int = None,
        Tags: List[TagTypeDef] = None,
        TransitiveTagKeys: List[str] = None,
        ExternalId: str = None,
        SerialNumber: str = None,
        TokenCode: str = None,
    ) -> AssumeRoleResponseTypeDef:
# [Client.assume_role documentation](https://boto3.amazonaws.com/v1/documentation/api/1.16.54/reference/services/sts.html#STS.Client.assume_role) 
```
Only `RoleArn` and `RoleSessionName` are marked as `[REQUIRED]`, the rest should be `Optional[...]` I think

**Comment by vemel** [comment]
Thank you for your report!

This is intentional because it is not always safe to pass `None` to optional arguments. I could not find a way to cross-check if it is safe for a particular method, so for now, I just do not add `Optional` annotation. 

This can change in future versions, so I mark it as an enhancement.

**Comment by vemel** [comment]
There is some progress on this issue. I started to build a hardcoded list of arguments where it is not safe to pass `None`.

So, hopefully by the next version, `Optional` annotation will be added where it is safe to pass `None`

**Comment by mbode** [comment]
We have encountered a similiar issue. To be specific, e.g. in `CloudWatchLogsClient.filter_log_events`, it seems safe to pass `None` for some of the non-required parameters. Is there any progress on the `Optional` annotations? Is there something we could do to support that effort?

**Comment by vemel** [comment]
Hello @mbode ,

I tried different approaches and the only suitable is to keep a hardcoded list of params that do not allow passing `None`. So, I am planning to mark all params as `Optional` and have a list of parameters that are not `Optional`.

**Comment by mbode** [comment]
Hello @vemel, thanks for pointing that out! We will have to look into why this hasn't lead to problems yet. Your effort has already helped us a lot, thanks for providing this library!
