### ISSUE TITLE
Clarify installation instructions for PyCharm

### ISSUE THREAD

**Issue by tuukkamustonen** [vemel/mypy_boto3_builder#65]
Hey there, thanks for the awesome package! Using `boto3` with type hints is just... lovely.

The [boto3-stubs docs for PyCharm](https://pypi.org/project/boto3-stubs/#pycharm) suggest to locally build the stubs:

> Install boto-stubs with services you use in your environment: python -m pip install 'boto3-stubs[s3,ec2]'
> Install mypy_boto3_builder: pip install mypy_boto3_builder
> Generate stubs in <project_root>/typings directory for services you use
> python -m mypy_boto3_builder --installed --skip-services typings -d -s s3 ec2
> Add <project_root>/typings folder to your Interpreter Paths
> Since stubs are stored in your project root, you do not need to re-generate them after update.

But I've never had to do this, as I think the package comes with the types pre-built? If so, why is there instruction to manually build the types?

---

I'm asking because I recently bumped version of `boto3` and `boto3-stubs` alongside, and I had to re-make the imports after the version bump (delete old line, add the same line back, and the error marker was removed... weird). Now that I added a new stub package (`boto3-stubs[iot-data]`) PyCharm finds it, I can navigate to it, and even auto-import it, but after the import, PyCharm somehow doesn't recognize it anymore. It shows like this:

![image](https://user-images.githubusercontent.com/94327/104913266-03e15e80-5996-11eb-90d4-6347b1f6ebbd.png)

**Comment by vemel** [comment]
Hello,

This is an optional step, because PyCahrm is very slow in revealing types for Literal overloads, and `boto3.client/session` functions use them heavily.

If you added a new package, you should rebuild local type stubs:

```bash
python -m mypy_boto3_builder --installed --skip-services typings -d -s s3 ec2 iot-data
```

I should definitely clarify instructions, will do!

**Comment by tuukkamustonen** [comment]
If it's optional step, it probably doesn't explain the odd behavior I am witnessing.

It must be some cache issue with PyCharm - I already tried invalidating cache (via `File > Invalidate caches / restart`) but it didn't help. I wonder what directory I should flush.

Could you clarify what you mean by "PyCharm is very slow in revealing types for Literal overloads"? I mean, if I already have the (correct) stubs in disk, PyCharm should just pick those up. How would local types (in `typing/` directory) work any better?

**Comment by vemel** [comment]
`boto3-stubs` package has overloads of `boto3.client/session` and `boto3.Session.client/session` for *all* 200+ boto3 services. Unfortunately, PyCharm consumes too much RAM and CPU while trying to automatically reveal types for your `boto3.client` etc. return values. mypy and pyright work as they should, so this is an issue in PyCharm.

To avoid this issue, you can generate your own `boto3-stubs` package locally in your `<project_root>/typings` folder only with services you use (e.g. `s3`, `ec2` and `iot-data`, so you have only 3 overloads instead of 200+). Also, do not forget to specify `typings` folder in PyCharm as an extra path for packages lookup. This way, even if you have `boto3-stubs` installed in your site-packages, PyCHarm will use a local version and perform way faster.

The downside is that if you add our remove subpackages (e.g. you want to add `pip install 'boto3-stubs[dynamodb]'`), you have to regenerate your `boto3-stubs` in `<project_root>/typings` folder.

```bash
python -m mypy_boto3_builder --installed --skip-services typings -d -s s3 ec2 iot-data dynamodb
```

**Comment by tuukkamustonen** [comment]
So PyCharm prefers local packages over those in `site-packages` directory? Fair enough, good to know! I do remember the [early struggles around this](https://github.com/vemel/mypy_boto3/issues/4), and that you found a compromise to overcome these issues.

I think what's interesting/weird here is that I initially had exactly zero performance problems (bootstrapping a new project that uses boto3 stubs). So even if I have those 200+ `Literal` `overloads` there, it didn't seem to be a problem. Only after upgrading the version of the stubs, the issues started. I initially thought it would be a caching issue in PyCharm, but then I realize something may have also changed in `boto3-stubs` package (between versions `1.14.51.0` and `1.16.55`). I know this is way too vague to work with, but I'll chime in if I find something.

In any case, I will try your suggestion to build the local overrides next (tomorrow)!

**Comment by tuukkamustonen** [comment]
With:

```
$ pip list | grep -i boto3
boto3                         1.16.55
boto3-stubs                   1.16.55.0
mypy-boto3-builder            3.3.0
mypy-boto3-events             1.16.55.0
mypy-boto3-iot                1.16.55.0
mypy-boto3-iot-data           1.16.55.0
mypy-boto3-logs               1.16.55.0
mypy-boto3-s3                 1.16.55.0
mypy-boto3-secretsmanager     1.16.55.0
mypy-boto3-sqs                1.16.55.0

$ pip install -U mypy-boto3-builder
...

$ pip list | grep -i mypy-boto3-builder
mypy-boto3-builder            3.3.0

$ python -m mypy_boto3_builder --installed --skip-services typings -d -s events iot iot-data logs s3 secretsmanager sqs
09:30:46 mypy_boto3_builder: INFO     Service amp is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service amplifybackend is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service appintegrations is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service auditmanager is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service connect-contact-lens is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service customer-profiles is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service devops-guru is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service ecr-public is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service emr-containers is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service greengrassv2 is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service healthlake is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service iotdeviceadvisor is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service iotfleethub is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service iotwireless is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service location is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service lookoutvision is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service mwaa is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service sagemaker-edge is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service sagemaker-featurestore-runtime is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Service wellarchitected is not fully supported.
09:30:46 mypy_boto3_builder: INFO     Bulding version 1.16.55
09:30:46 mypy_boto3_builder: INFO     Generating mypy_boto3 module
09:30:46 mypy_boto3_builder: DEBUG    Parsing master
09:30:48 mypy_boto3_builder: DEBUG    Writing master to typings
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/__init__.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/__main__.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/py.typed
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/version.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/main.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_init.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_session.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_init_gen.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_session_gen.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_init_stub.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/boto3_session_stub.py
09:30:49 mypy_boto3_builder: DEBUG    Updated typings/mypy_boto3/submodules.py
09:30:49 mypy_boto3_builder: INFO     Generating boto3-stubs module
09:30:49 mypy_boto3_builder: DEBUG    Parsing boto3 stubs
09:30:50 mypy_boto3_builder: DEBUG    Writing boto3 stubs to typings
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/py.typed
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/__init__.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/__init__.py
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/session.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/__main__.py
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/version.py
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/utils.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/compat.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/exceptions.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/params.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/model.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/response.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/factory.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/action.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/collection.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/__init__.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/resources/base.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/dynamodb/types.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/dynamodb/conditions.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/dynamodb/transform.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/dynamodb/__init__.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/dynamodb/table.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/ec2/create_tags.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/ec2/__init__.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/ec2/delete_tags.pyi
09:30:56 mypy_boto3_builder: DEBUG    Updated typings/boto3-stubs/docs/__init__.pyi
09:30:56 mypy_boto3_builder: INFO     Completed

$ ll typings/boto3-stubs/
total 444K
-rw-rw-r-- 1 musttu musttu  277 tammi  20 09:30 compat.pyi
drwxrwxr-x 2 musttu musttu 4,0K tammi  20 09:30 docs/
drwxrwxr-x 2 musttu musttu 4,0K tammi  20 09:30 dynamodb/
drwxrwxr-x 2 musttu musttu 4,0K tammi  20 09:30 ec2/
-rw-rw-r-- 1 musttu musttu 1,3K tammi  20 09:30 exceptions.pyi
-rw-rw-r-- 1 musttu musttu 129K tammi  20 09:30 __init__.py
-rw-rw-r-- 1 musttu musttu 127K tammi  20 09:30 __init__.pyi
-rw-rw-r-- 1 musttu musttu  310 tammi  20 09:30 __main__.py
-rw-rw-r-- 1 musttu musttu    7 tammi  20 09:30 py.typed
drwxrwxr-x 2 musttu musttu 4,0K tammi  20 09:30 resources/
-rw-rw-r-- 1 musttu musttu 144K tammi  20 09:30 session.pyi
-rw-rw-r-- 1 musttu musttu  839 tammi  20 09:30 utils.pyi
-rw-rw-r-- 1 musttu musttu   55 tammi  20 09:30 version.py
```

So, it only created stubs for `dynamo` and `ec2`? Why doesn't it create all the other services (`events sqs` etc.)?

I'm running python 3.7.9 and it only installs `boto3-mypy-builder==3.3.0`. Later releases cannot be installed, perhaps they are runnable with 3.8+ only? Though the main page states that:

![image](https://user-images.githubusercontent.com/94327/105143102-0feb2e80-5b04-11eb-8ef8-cfb55158192a.png)

**Comment by tuukkamustonen** [comment]
I realized that I had the `boto3-stubs` raw/base package installed, which probably explains the performance issues. How it ended up being installed is `pip-tools` issue (specifying `boto3-stubs=xxx` in _constraints_ file actually lead up the package being _installed_, odd).

Having `boto3-stubs` package also messes up with the imports in PyCharm. With `boto3-stubs` installed, auto-import attempts to import clients `from mypy_boto3_iot import IoTClient`, but with `boto3-stubs` uninstall, auto-import attempts to import `from mypy_boto3_iot.client import IoTClient`. The former works in runtime, but PyCharm marks it as error, while the latter works in both cases.

`mypy_boto3_iot/__init__.pyi` defines just correctly:

![image](https://user-images.githubusercontent.com/94327/105686672-2f1cfe00-5f00-11eb-8562-e01cddc709cd.png)

...so I don't know why PyCharm doesn't understand the import from there, but I think it's PyCharm issue anyway (as it works in runtime). It's just that the existence of `boto3-stubs` package makes PyCharm import from there, instead of `.client` sub-module (which works better).

---

In the end, I would suggest:

1. Document that compiling the types locally is optional, and that _you should never need to do it_. Explain how/when it might be a good idea to do it (I'm still not sure when).
2. Emphasize that people shouldn't accidentally install the `boto3-stubs` base package. `pip` constraints and things work sometimes too magically, and mistakes happen (like for me).

**Comment by tuukkamustonen** [comment]
Uh, seems like I spoke to soon.

I do think that removal of `boto3-stubs` base package fixes the performance issues, but it seems to come installed as a requirement for any extra-package (e.g. `boto3-stubs[iot]`).

What does `boto3-stubs` contain? Is it really necessary to have present?

**Comment by vemel** [comment]
The main reason is that generating code while `pip install` is a very bad practice. And unfortunately you cannot keep overloads in different files, they all should be in `boto3-stubs/__init__.pyi`, otherwise type checkers cannot find overloads. It used to be this way, so installing `boto3-stubs[s3]` would generate only overloads for `boto3.client("s3")`. Now it has annotations for all services, so no more code generation. mypy and pyright and happy with this change, only PyCharm has the issue.

THank you for mentioning that you removed `boto3-stubs` package from site-packages, this way you can be sure that you use a local package.

**Comment by tuukkamustonen** [comment]
Hi, forgot to reply here!

In short, thanks for explaining the rationale. I don't see any other way around it either, and yeah, I agree that generating code during installation sounds hacky, so better current way.

> mypy and pyright and happy with this change, only PyCharm has the issue.

Did you ever open a ticket for them about it? I will, if you haven't already. The problem is easy to reproduce, so it should be straightforward.

> THank you for mentioning that you removed `boto3-stubs` package from site-packages, this way you can be sure that you use a local package.

Hmm, I'm not sure what you mean by a "local" package? I did not compile the type annotations locally, if that's what you mean. I didn't do that, because that shouldn't be needed.

What I'm maybe suggesting is that could `boto3-stubs` package made optional, instead of having it as base package? So that `boto3-stubs[s3, ec2, etc]` packages would NOT depend on `boto3-stubs`? Then, you would install `boto3-stubs` only if you're interested about those overloads (=not having to annotate the clients explicitly)?

In my case, I know have to uninstall `boto3-stubs` each time I sync my dependencies, which is kinda annoying (but doable). I do understand, that it's a PyCharm-only issue, and will get fixed eventually (once we raise a ticket about it), but currently I, and everyone else who uses PyCharm, will suffer from it.

Or, at least document that on PyCharm users should manually remove `boto3-stubs`, to avoid performance issues.

**Comment by vemel** [comment]
No, I did not open an issue for PyCHarm, I do not use it at all.

`boto-stubs` is already optional, you can install only service packages, like `pip install mypy-boto3-s3 mypy-boto3-ec2`. If you list them in your `requirements-dev.txt` this way, `boto3-stubs` will not be installed.

Probably, this worth mentioning in docs as well.

**Comment by tuukkamustonen** [comment]
> No, I did not open an issue for PyCHarm, I do not use it at all.

Alright, I will open one. Let's hope they give it some attention.

> `boto-stubs` is already optional, you can install only service packages, like `pip install mypy-boto3-s3 mypy-boto3-ec2`. If you list them in your `requirements-dev.txt` this way, `boto3-stubs` will not be installed.
>
> Probably, this worth mentioning in docs as well.

Yeah, definitively!

It's so obvious now, because true, when you do `pip install whatever-package[extras]` then `whatever-package` gets installed, always. But I didn't realize you can directly install `mypy-boto3-<service>` packages. So simple.

And while that might be irrelevant normally, it's good to mention the workaround now that PyCharm dies to `boto3-stubs`.

Feel free to close this ticket once you push the README updates :) Thanks again!

**Comment by tuukkamustonen** [comment]
There seems to be already a PyCharm ticket: https://youtrack.jetbrains.com/issue/PY-40997
