### ISSUE TITLE
[DOC] "Explicit type annotations" section contains invalid imports

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#66]
**Describe the bug**
Something weird seems to have happened with the [documentation](https://pypi.org/project/boto3-stubs/):

- `import EC2Client` which as far as I can tell should be `from mypy_boto3_ec2 import EC2Client`.
- `import import`, which I don't think is ever possible.

**Comment by vemel** [comment]
Thank you, will fix!

**Comment by vemel** [comment]
Turns out, I was applying isort/black to all generated files, including `README.md`. Never try this at home!

**Comment by vemel** [comment]
This is way better: https://pypi.org/project/boto3-stubs/

**Comment by l0b0** [comment]
Fantastic handling, thank you!
