### ISSUE TITLE
[BUG] GetObjectOutputTypeDef and documentation disagree about Body type

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#67]
**Describe the bug**
mypy_boto3_s3's type_defs.py defines `GetObjectOutputTypeDef["Body"]` as having type `IO[bytes]`, but the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_object) says it's `StreamingBody`.

**To Reproduce**
1. Install mypy-boto3-dynamodb
2.  Run mypy on the following code sample

```python
import boto3

s3_client = boto3.client("s3")
url_stream = s3_client.get_object(Bucket="bucket", Key="key")["Body"]
url_stream.iter_chunks()
```
3. Actual mypy output

```
test.py:5: error: "IO[bytes]" has no attribute "iter_chunks"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

**Expected mypy-output**

Nothing.

**Additional context**

Arch Linux

boto3-stubs installed using the following Poetry configuration:

```
[tool.poetry.dev-dependencies.boto3-stubs]
version = "*"
extras = ["batch", "dynamodb", "lambda", "s3", "stepfunctions"]
```

boto3 1.17.1.

**Comment by vemel** [comment]
Makes sense, will be fixed in the next release. Thank you for the report!

**Comment by vemel** [comment]
Fixed for all services and also updated integration tests for `s3`. Please let me know if the latest version works as it should for you.
