### ISSUE TITLE
[BUG] 'Chain' is missing __jsii_proxy_class__ 'IChainable' protocol member

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#68]
**Describe the bug**

Previously type validated code is failing with errors like this after upgrading to 

```text
error: Argument 1 to "otherwise" of "Choice" has incompatible type "Chain"; expected "IChainable"  [arg-type]
note: 'Chain' is missing following 'IChainable' protocol member:
note:     __jsii_proxy_class__
```

**To Reproduce**

1. Check out https://github.com/linz/geospatial-data-lake/pull/64
2. Remove `# type: ignore[arg-type]` comments in datalake/processing_stack.py
3. Run mypy

**Actual mypy output**

```
$ mypy datalake/processing_stack.py
datalake/processing_stack.py:151: error: Argument 1 to "otherwise" of "Choice" has incompatible type "Chain"; expected "IChainable"  [arg-type]
datalake/processing_stack.py:151: note: 'Chain' is missing following 'IChainable' protocol member:
datalake/processing_stack.py:151: note:     __jsii_proxy_class__
datalake/processing_stack.py:168: error: Argument "definition" to "StateMachine" has incompatible type "Chain"; expected "IChainable"  [arg-type]
datalake/processing_stack.py:168: note: 'Chain' is missing following 'IChainable' protocol member:
datalake/processing_stack.py:168: note:     __jsii_proxy_class__
Found 2 errors in 1 file (checked 1 source file)
```

**Expected mypy-output**

Nothing.

**Additional context**

- boto3-stubs 1.17.5.0
- boto3 1.17.5
- mypy 0.800
- Arch Linux

**Comment by vemel** [comment]
Sorry for the late response. I tried to fix the issue, but no luck so far, because generation follows botocore specs. I probably can stub it manually.

**Comment by l0b0** [comment]
Thank you for the effort! I've simply marked the various mismatches as `# type: ignore[arg-type]`.
