### ISSUE TITLE
Support PEP 655

### ISSUE THREAD

**Issue by ITProKyle** [vemel/mypy_boto3_builder#70]
While [PEP 655](https://www.python.org/dev/peps/pep-0655/) is still a draft, type checkers like [pyright/pylance](https://github.com/microsoft/pyright/issues/1584#issuecomment-794953872) have already adopted rules to enforce it.

Currently, the way most are constructed, `TypedDict`s require complex `if "field" in instance` conditional blocks or chained `.get("field", {})` calls to comply.

While the PEP is not yet ratified, it is worth starting the discussion to find a solution.

**Comment by tekumara** [comment]
As mentioned [here](https://github.com/microsoft/pyright/issues/1693#issuecomment-808754716) it's possible to solve without PEP 655 by using inheritance.

**Comment by vemel** [comment]
Awesome idea! Will do it in the next release

**Comment by vemel** [comment]
All TypedDicts in new version use the technique described in https://github.com/microsoft/pyright/issues/1693#issuecomment-808754716

Thank you for the idea! Probably it can be simplified to use just two TypedDicts

```python
class _MyDict(TypedDict, required=True):
   required_field: str
   
class MyDict(_MyDict, required=False):
   optional_field: str
   ```

**Comment by ITProKyle** [comment]
Thanks for the quick turnaround.
