### ISSUE TITLE
[BUG] Possibly incorrect annotations for mypy_ec2_boto3.Instance.network_interfaces

### ISSUE THREAD

**Issue by sfleischman105** [vemel/mypy_boto3_builder#73]
**Describe the bug**
It seems that `mypy_ec2_boto3` might have incorrect annotations when using `Instance.network_interfaces`. The [ec2.Instance](https://boto3.amazonaws.com/v1/documentation/api/1.17.62/reference/services/ec2.html#EC2.Instance.network_interfaces) docs say that `network_interfaces` are a reference on a `Instance`: 
> These are the resource's available references:
> * classic_address
> * image
> * key_pair
> * network_interfaces
> * placement_group
> * subnet
> * vpc

And [ec2.Instance.network_interfaces](https://boto3.amazonaws.com/v1/documentation/api/1.17.62/reference/services/ec2.html#EC2.Instance.network_interfaces) say that:
> network_interfaces
> (NetworkInterface) The related network_interfaces if set, otherwise None.

Which isn't exactly descriptive of the type. We can manually check the types by loading up an existing instance that contains a network interface, and use boto3 to check what the output of `Instance.network_interfaces` is:
```python
import boto3

ec2 = boto3.resource('boto3')
instance = ec2.Instance('i-0123456789abcdef0')

interfaces = instance.network_interfaces
print(type(interfaces))     # prints 'list'
print(type(interfaces[0]))  # prints 'boto3.resources.factory.ec2.NetworkInterface'
```

boto3 returns a `List[NetworkInterface]`. If I do the steps below, we can see the disagreement between the type annotations and boto3.

**To Reproduce**
1. Install 'boto3-stubs[...]'
2.  Run mypy on the following code sample

```python
import boto3
from typing import List
from mypy_boto3_ec2.service_resource import Instance, NetworkInterface

def get_instance_interfaces(instance: Instance) -> List[NetworkInterfaces]
    return instance.network_interfaces
```

3. Actual mypy output

```bash
instance_interfaces.py:6: Incompatible return value type (got "NetworkInterface", expected "List[NetworkInterface]")  [return-value]
```

**Expected mypy-output**

Expected no lint errors.

**Additional context**

This is was on Ubuntu 18.04, with the following versions of the packages:
```
boto3-stubs==1.17.62
boto3==1.17.62
mypy-boto3-ec2==1.17.62
```

This might be a trickier one to solve, as there might not be a clear distinction as to when a service's resource is a `List[<Resource>]`, or simply a `<Resource>`. Perhaps this is due to legacy `boto3` behavior where resource collections didn't exist.

**Comment by vemel** [comment]
Hello,

It is a collection as I see: https://github.com/vemel/mypy_boto3_builder/blob/master/service_docs/mypy_boto3_ec2/service_resource.md#ec2serviceresourcenetwork_interfaces

I will check how it works in this case, as I do not use collections that often. I would recommend to rewrite your code to iterators:

```python
from typing import Iterator, List
from mypy_boto3_ec2.service_resource import Instance, NetworkInterface

def get_instance_interfaces(instance: Instance) -> Iterator[NetworkInterface]
    yield from instance.network_interfaces
    
# or if you want a list
def get_instance_interfaces(instance: Instance) -> List[NetworkInterface]
    return list(instance.network_interfaces)
```

Let me know what you think and if it solves your issue! Also, if you have time, please check these auto-generated docs that I have just pushed. They should make things a lot easier.

**Comment by kleschenko** [comment]
I've just discovered the same issue, and seems like @sfleischman105 is correct here: `instance.network_interfaces` is not a collection in `boto3`, it is an actual list

**Comment by kleschenko** [comment]
Here is also [a link to the documentation](https://boto3.amazonaws.com/v1/documentation/api/1.17.62/reference/services/ec2.html#EC2.Instance.network_interfaces_attribute), which says that it should be a list
