### ISSUE TITLE
[BUG] pyright  unable to infer some types

### ISSUE THREAD

**Issue by ITProKyle** [vemel/mypy_boto3_builder#74]
This was discovered when using the value of `boto3.client("cloudformation").create_change_set()["ExecutionStatus"]` - pyright is reporting the value as unknown. However, I don't think it is restricted to this call/return type as I am seeing other strange type errors throughout.

These type errors do not appear when using boto3-stubs version 1.17.56 but it appeared when updating the dependencies in my lock file which installed version 1.17.69.

When comparing the stubs produced by both versions, pyright shows the following error for the newer stubs - `Type of "ResponseMetadata" could not be determined because it refers to itself (PylancereportGeneralTypeIssues)`. I _think_ this is the root cause - it was introduced by changing how the `TypedDict`s are being built/output. The older, working version uses the [alternative syntax](https://www.python.org/dev/peps/pep-0589/#alternative-syntax) while the new version uses the [class syntax](https://www.python.org/dev/peps/pep-0589/#class-based-syntax). The reason for moving to the class syntax is understandable - enabling inheritance for backward compatible required/optional keys. This means that it's not reasonable to revert back to alternative syntax.

A potential solution would be rename the `ResponseMetadata` TypedDict class to `ResponseMetadataTypeDef` (mirroring what has already been done for some other TypedDicts) but, this would be a breaking change for anyone importing and trying to use `ResponseMetadata`.

**Additional context**

OS: macOS 11
Python: 3.8.5
pyright: 1.1.138

**Comment by vemel** [comment]
Thank you for the report!

Yes, looks like a recursive type annotation, that `TypedDict` does not support. WIll fix it today.

**Comment by vemel** [comment]
@ITProKyle so, the issue was introduced because I switched to class-based `TypedDict` rendering. Unfortunately, this creates conflicts between `TypedDict` key names and `Literal` names. Reverted back to old-style rendering. `ResponseMetadata` renamed to `ResponseMetadataTypeDef` as well.

I have just pushed a post-release `boto3-stubs 1.17.70.post1`. Please let me know if it works as you expected. And let me know if there is anything else that needs improvement.
