### ISSUE TITLE
ImportError: cannot import name 'BundleTaskCompleteWaiter' from 'mypy_boto3_ec2.paginator'

### ISSUE THREAD

**Issue by ayalganem55** [vemel/mypy_boto3_builder#76]
**Describe the bug**
ImportError: cannot import name 'BundleTaskCompleteWaiter' from 'mypy_boto3_ec2.paginator'

**To Reproduce**
1. pip install mypy-boto3-ec2 boto3
2.  Run mypy on the following code sample

```python
from mypy_boto3_ec2 import Client, ServiceResource
```

3. Actual mypy output
```
ImportError: cannot import name 'BundleTaskCompleteWaiter' from 'mypy_boto3_ec2.paginator'
```

**Expected mypy-output**
```
To import the mypy_boto3_ec2
```

**Additional context**
installing the latest mypy_boto3_ec2 (version 1.17.72)

**Comment by dan-hook** [comment]
There's a similar bug in mypy_boto3_s3.  I don't know in which version this changed, but in 1.17.64.2 we see that mypy_boto3_s3.client imports waiters like this:

`
from mypy_boto3_s3.waiter import (
    BucketExistsWaiter,
    BucketNotExistsWaiter,
    ObjectExistsWaiter,
    ObjectNotExistsWaiter,
)
`
But in 1.17.72, the Waiter imports are incorrectly grouped with the paginator imports:
`
from .paginator import (
    BucketExistsWaiter,
    BucketNotExistsWaiter,
    ListMultipartUploadsPaginator,
    ListObjectsPaginator,
    ListObjectsV2Paginator,
    ListObjectVersionsPaginator,
    ListPartsPaginator,
    ObjectExistsWaiter,
    ObjectNotExistsWaiter,
)`

**Comment by dannosaur** [comment]
Same issue in `mypy_boto3_iam.client`, errors out trying to import `from .paginator import InstanceProfileExistsWaiter`, sourced from the following import in my own code; `from mypy_boto3_iam.service_resource import Role`.

Ends up throwing the following error;

```
  File "/usr/local/lib/python3.9/site-packages/mypy_boto3_iam/__init__.py", line 86, in <module>
    from .client import IAMClient
  File "/usr/local/lib/python3.9/site-packages/mypy_boto3_iam/client.py", line 31, in <module>
    from .paginator import (
ImportError: cannot import name 'InstanceProfileExistsWaiter' from 'mypy_boto3_iam.paginator' (/usr/local/lib/python3.9/site-packages/mypy_boto3_iam/paginator.py)
```

Even PyCharm can't navigate to the definition, so it's definitely missing/broken.

**Comment by johnnadratowski** [comment]
Same issue here, with `BucketExistsWaiter`:

```
.venv/lib/python3.9/site-packages/mypy_boto3_s3/client.py:33: in <module>
from .paginator import (
ImportError: cannot import name 'BucketExistsWaiter' from 'mypy_boto3_s3.paginator' (/var/lib/jenkins/workspace/Data_Operations-IHM_Integration/IHM_Integration_01_Pull_Requests/.venv/lib/python3.9/site-packages/mypy_boto3_s3/paginator.py)
```

**Comment by vemel** [comment]
Thank you for the report.

Yes, imports in `client.py` were incorrect.  I am going to release `1.17.72.post1` with a bug fix.

**Comment by vemel** [comment]
Discussion moved to https://github.com/vemel/mypy_boto3_builder/issues/75
