### ISSUE TITLE
Dependencies out-of-sync between poetry and setuptools

### ISSUE THREAD

**Issue by maresb** [vemel/mypy_boto3_builder#77]
In `setup.cfg` there is
```conf
install_requires =
    black>=21.4b2
    boto3
    isort>=5.6.4
    jinja2>=2.10.3
    pyparsing>=2.4.7
    md_toc
    mdformat
```
while in `pyproject.toml` there is
```conf
[tool.poetry.dependencies]
python = "^3.8"
pip = "*"
black = "*"
boto3 = "*"
isort = "^5.6.4"
jinja2= "^3.0.1"
pyparsing = "^2.4.7"
md_toc = "*"
mdformat = "^0.7.5"
```
The `conda` build was failing because I was looking at the dependencies from `setup.cfg` instead of `pyproject.toml`, and it installed `jinja2` version `2`.

Since you are using poetry, would it be possible to get rid of setuptools, or do you still need it for something?

**Comment by vemel** [comment]
I have just pushed a fix to master. Is a new release required?

**Comment by maresb** [comment]
Cool, thanks! No new release is required.

**Comment by maresb** [comment]
Out of curiosity, why maintain both `poetry` and `setuptools`?

**Comment by vemel** [comment]
Removed `install_requires`, should be good now. Thank you for the suggestion! And let me know if conda build works.

**Comment by vemel** [comment]
Makes sense. I will spend some time on it during the weekend. If you have time to submit a PR - that would be awesome! Thank you for helping me with the package.

**Comment by maresb** [comment]
No problem! My PR would simply amount to deleting `setup.cfg` and `setup.py`, so I don't think it's worth actually making such a PR. You would have to test whether or not it breaks something in your workflow.

**Comment by vemel** [comment]
I still depend on `setup.cfg`, so let's keep it here for now. Since there is no conflict anymore, I am closing this issue.

Please create a new issue if you have any other suggestions on how to improve the release process
