### ISSUE TITLE
Wrong type for boto3 Session argument

### ISSUE THREAD

**Issue by corleyma** [vemel/mypy_boto3_builder#78]
The argument `botocore_session` should be of type `BotocoreSession`, not `Session`:
https://github.com/vemel/mypy_boto3_builder/blob/b79d6b14d5203ce7e541af845eaa80687a33900c/mypy_boto3_builder/templates/boto3-stubs/boto3-stubs/session.pyi.jinja2#L12

**Comment by vemel** [comment]
Thank you for the report. I will fix this.

**Comment by vemel** [comment]
I have just released a fix for this issue. So, the next version of `boto3-stubs` will be built with this fix incluided. Thank you and let me know if it works as it should for you.
