### ISSUE TITLE
[BUG] Boto3 types not resolved for the flavor `boto3.session.Session()`

### ISSUE THREAD

**Issue by rajdeep87** [vemel/mypy_boto3_builder#81]
**Describe the bug**
Using the boto3-stubs, the following flavor of boto3 client is not resolved.
```python
def get_client(self):
        session = boto3.session.Session()
        s3_url = os.environ.get('S3_ENDPOINT_URL')
        return session.client('s3', region_name=self.aws_region, endpoint_url=s3_url)`
```

**To Reproduce**
1. Install 'boto3-stubs 1.17.89'
2.  Run mypy on the following code sample

```python
import boto3

class ClientTest():
def get_client(self):
        session = boto3.session.Session()
        return session.client('s3', region_name=self.aws_region, endpoint_url=s3_url)

def get_ip(self):
        s3_client = self.get_client()
```

3. Actual mypy output

```
The type of "s3_client" is shown as "Any" inside the method "get_ip"
```

**Expected mypy-output**

```
The type of "s3_client" should be "S3Client"
```

**Additional context**
`OS` - MAC OS, 
`boto3-stubs` - 1.17.89
`boto3` version - 1.0.

**Comment by vemel** [comment]
This is because `mypy` does not reveal types in not-annotated functions and methods. If we move the code outside of methods, it works as it should:

```python
import boto3

session = boto3.session.Session()
client = session.client("s3", region_name="aws_region", endpoint_url="s3_url")
reveal_type(client)
```

mypy output:

```
test.py:6: note: Revealed type is 'mypy_boto3_s3.client.S3Client'
```

**Comment by rajdeep87** [comment]
Thanks for your response! I have few follow-up questions.
1)  I am using `Pylance` extension with VSCode to determine the boto3 client for the earlier posted example (also shown below). I have moved the code outside of methods. However, the type of `client` could not be inferred. Any suggestion?

```python
import boto3

session = boto3.session.Session()
client = session.client("s3", region_name="aws_region", endpoint_url="s3_url") 
```


1) I am using `Pylance` extension with VSCode to determine the boto3 client types across files? For example, for the below 2 files, using VSCode, the type of "s3_client" and "s3_resource" in the file "design.py" could not be resolved. Any suggestions?
 

**Content of file named resource.py**
```python
import boto3
s3_client = boto3.client('s3')
s3_resource = boto3.resource('s3')
```


**Content of file named "design.py"** 
```python
from resource import s3_resource, s3_client

class Database(object):

  def __init__(self, name):
    self.name = name
    self.bucket = s3_resource.Bucket(self.name)

  @property
  def tables(self) -> list:
    result = s3_client.list_objects(Bucket=self.name, Delimiter="/")
```

2) Would `pyright` help to determine the boto3 client types across files? For example, for the above 2 files, would pyright when configured with boto3-stubs can determine the type of "s3_client" and "s3_resource" in the file "design.py" ?

**Comment by vemel** [comment]
Yes, `pyright` should be able to reveal types correctly in this case, so `Pylance` should provide code auto-complete as well. I just tested your code, works as it should.

**Comment by rajdeep87** [comment]
Thanks for testing the examples. Good to know that this worked in your environment. I am using `Pylance` extension with VSCode and set the `python.languageServer` to `Pylance`. The `boto3` types for both the examples 1) and 2) above was not resolved. Am I missing some steps in my testing environment. Any suggestion would be appreciated. Thanks!

**Comment by vemel** [comment]
Do you have `mypy_boto3_s3` submodule installed? You should install submodules for each boto3 service you use.

```bash
# installs boto3-stubs, botocore-stubs, mypy_boto3_s3
pip install boto3-stubs[s3]
```

Let me know if it works for you

**Comment by rajdeep87** [comment]
Yes! The `mypy_boto3_s3` is installed. When I ran the following in command line, it shows the following.

```
% python3.8 -m pip install boto3-stubs[s3]
```

```
Requirement already satisfied: boto3-stubs[s3] in /usr/local/lib/python3.8/site-packages (1.16.2.0)
Requirement already satisfied: mypy-boto3-s3==1.16.2.0; extra == "s3" in /usr/local/lib/python3.8/site-packages (from boto3-stubs[s3]) (1.16.2.0)
```

**Comment by vemel** [comment]
I am not sure why. Please try using explicit type annotations in `resource.py`

```python
import boto3
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client, S3ServiceResource
else:
   S3Client = object
   S3ServiceResource = object

s3_client: S3Client = boto3.client('s3')
s3_resource: S3ServiceResource = boto3.resource('s3')
```

However, with the latest `Pylance/pyright` types are resolved correctly.

Could you please run `pyright` from this code:

```python
import boto3
s3_client = boto3.client('s3')
s3_resource = boto3.resource('s3')

reveal_type(s3_client) # should be S3Client
reveal_type(s3_resource) # should be S3ServiceResource
```

Let me know if types are not revealed correctly.

**Comment by rajdeep87** [comment]
Thanks a lot for all the great suggestions. This is very helpful! I will respond to each of the issues separately. 

**Experiment 1:**
 
```python
import boto3
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client, S3ServiceResource
else:
   S3Client = object
   S3ServiceResource = object

s3_client: S3Client = boto3.client('s3')
s3_resource: S3ServiceResource = boto3.resource('s3')
```

With explicit type annotation, `Pylance/pyright` types are resolved correctly. So, this is resolved. 


**Experiment 2:**

```python
import boto3
s3_client = boto3.client('s3')
s3_resource = boto3.resource('s3')

reveal_type(s3_client) # should be S3Client
reveal_type(s3_resource) # should be S3ServiceResource
```

Running `pyright` on this code is able to resolve the types correctly. So, this is resolved.

**Comment by vemel** [comment]
Okay, good. Must be something with imports then. What if you move

```python
reveal_type(s3_client) # should be S3Client
reveal_type(s3_resource) # should be S3ServiceResource
```

to `design.py`? Does it still work?

**Comment by rajdeep87** [comment]
Good point. Yes, I tested the code and looks like the types of `s3_client` as well as `s3_resource` are correctly resolved in the file `design.py`. It was an issue with the imports. Thanks a lot for your help and suggestions!

**Comment by rajdeep87** [comment]
I have a follow-up question about type resolution. Consider the example below. I ran the example with `Pylance/pyright`. The types (obtained with `reveal_type`) are correctly resolved in the file `CodeB.py` and `CodeC.py`, but the type of `self.dynamodb_client` in `CodeA.py` denoted by `reveal_type(self.dynamodb_client)` could not be resolved. Is it a limitation or do I need to run `pyright`differently ? Any suggestion is appreciated. Thanks in advance! 


**Content of file named "codeA.py"**
```python
class JobsDAO:
    def __init__(self, ddb_resource_client):
        self.dynamodb_client = ddb_resource_client
        reveal_type(self.dynamodb_client) #type not resolved
```

**Content of file named "codeB.py"**
```python
from pythonboto3.sub.codeC import AWSClient
from pythonboto3.sub.codeA import JobsDAO

def get_jobs_dao():
    ddb_client = AWSClient.get_dynamodb_client()
    reveal_type(ddb_client) # type correctly resolved as DynamoDBServiceResource
    return JobsDAO(ddb_client)
```

**Content of file named "codeC.py"**
```python
import boto3
import os

class AWSClient:
    @staticmethod
    def get_region():
        return os.environ.get('AWS_REGION')

    @staticmethod
    def get_dynamodb_client():
        dynamodb = boto3.resource('dynamodb', region_name=AWSClient.get_region(), config=aws_client.DEFAULT_AWS_CONFIG)
        reveal_type(dynamodb)  # type correctly resolved as DynamoDBServiceResource
        return dynamodb
```

**Comment by vemel** [comment]
I believe you have to use explicit type annotations in `codeA.py`

```python
from mypy_boto3_dynamodb import DynamoDBClient

class JobsDAO:
    def __init__(self, ddb_resource_client: DynamoDBClient) -> None:
        self.dynamodb_client = ddb_resource_client
        reveal_type(self.dynamodb_client)
```

**Comment by rajdeep87** [comment]
Thanks for the suggestion. Yes, explicit type annotation helped in this case. Appreciate all your help and suggestions on this issue.
