### ISSUE TITLE
`mypy_boto3_cloudformation.literals.ResourceStatusType` missing valid values

### ISSUE THREAD

**Issue by ITProKyle** [vemel/mypy_boto3_builder#83]
This is **not** an issue with the builder but rather an issue with the data being used to build the stubs (https://github.com/boto/botocore/issues/1807). Until this has been resolved upstream, would it be possible to _patch_ the missing values in?

This is primarily an issue for return types when trying to do a comparison for one of the values missing from the upstream enum.

**Comment by ITProKyle** [comment]
Awesome! As always, thanks for the quick turnaround. Anything less than 2 years beats AWS on this one 🤦 .

**Comment by vemel** [comment]
I have just released `4.18.1` with the fix. So, `boto3-stubs 1.17.92` that should be out today will have a correct literal annotation.

It actually took slightly less than 2 years indeed...

**Comment by vemel** [comment]
Okay, all good: https://vemel.github.io/boto3_stubs_docs/mypy_boto3_cloudformation/literals.html#resourcestatustype

Let me know if it does not work as it should.
