### ISSUE TITLE
[BUG] "E0611: No name 'ClientErrorResponseError' in module" from pylint after upgrade

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#86]
**Describe the bug**
`from botocore.exceptions import ClientErrorResponseError, ClientErrorResponseTypeDef` results in errors like

> E0611: No name 'ClientErrorResponseError' in module 'mypy_boto3_s3' (no-name-in-module)

from pylint.

**Expected `pylint` output**

Nothing.

**Additional context**

Arch Linux, boto3-stubs 1.17.94, boto3 1.17.53. Relevant [pull request](https://github.com/linz/geostore/pull/791).

**Comment by vemel** [comment]
Thank you for the report. I will try to fix it today.

**Comment by vemel** [comment]
These types do not exist in `botocore`. The only thing I can do is to exclude them from `__all__` statement.

Since you cannot import types from stub files (`*.pyi`), options are:

- Add these type defs to every module and allow importing them
- Add the following code to your project and use it instead of importing:

```python
from typing import TypedDict, Dict, Any

class ClientErrorResponseError(TypedDict, total=False):
    Code: str
    Message: str

class ResponseMetadataTypeDef(TypedDict):
    RequestId: str
    HostId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, Any]
    RetryAttempts: int

class ClientErrorResponseTypeDef(TypedDict, total=False):
    Error: ClientErrorResponseError
    ResponseMetadata: ResponseMetadataTypeDef
```

**Comment by l0b0** [comment]
I'll opt for keeping [the current solution](https://github.com/linz/geostore/pull/791/files) of just annotating the lines with `# pylint:disable=no-name-in-module`. That way I can use the extremely handy `TypedDict`s in my test code rather than hard coding a bunch of `dict` keys.

**Comment by vemel** [comment]
THe next version of `botocore-stubs` should not have misleading exports, will be released tomorrow.
