### ISSUE TITLE
Allow non-strict version requirements for boto3-stubs and subpackages

### ISSUE THREAD

**Issue by maresb** [vemel/mypy_boto3_builder#87]
The conda-forge build of boto3-stubs always fails because the packages which it contains are never immediately available on conda-forge.

There is typically a delay of 1-1½ hours between a conda-forge package being built and it being downloadable. This is due to CDN delays.

Currently, each build requires human intervention to initiate a rebuild of the `boto3-stubs` package. If you could schedule it so that `boto3-stubs` is published with a delay of 2½-3 hours, that would ensure that the dependencies are available and allow automerge to take place without the need for human intervention.

Out of curiosity, is there a good reason for the daily builds? (It seems a bit excessive to me.)

**Comment by vemel** [comment]
`boto3-stubs` is published 1-2 hours after a new `boto3` version is released. Most of the packages do not have any changes compared to the previous version, but there is no way to check if the package has to be updated, so I upload all 270 services.

Probably, I can make requirements less strict to allow previous submodules versions in `boto3-stubs` requirements?

**Comment by maresb** [comment]
Thanks for the info @vemel!

I just had an idea on the conda-forge end for how we can solve it. If we put all the stubs into a single recipe, then it builds at the same time and there is no longer this problem. Let me look into that possibility.

**Comment by vemel** [comment]
Thank you! Let me know how it goes and if there is anything I can do to help you.

**Comment by vemel** [comment]
I have an idea. `boto3-stubs` package is always released after all `mypy-boto3-*` packages. So you can check if a new version of `borto3-stubs` package is available and build the corresponding submodule. So, all conda packages should have the same trigger condition. What do you think?

**Comment by maresb** [comment]
@vemel, thanks for the idea. I'm not sure I understand it though. :(  The conda-forge autoupdate bots are triggered by updates to PyPI, and I don't have any way to add conditions before they run. A symptom of the problem is that due to CDN delays, there's a period of up to two hours between when `mypy-boto3-*` is available on PyPI but not yet on `conda-forge`. Thus I'm not sure how I could implement it.

My previous idea was to use multiple PyPI source lines in a single recipe. (I always thought the rule was one source per recipe.) This way, we'd just have the `boto3-stubs` recipe and it would be able to output `boto3-stubs`, `boto3-stubs-essential`, as well as all of the `mypy-boto3-*` packages. And because everything would be under a single recipe, `conda` would be able to resolve the build order and make everything in a single step.

What really intrigues me is this possibility you raise:

> Probably, I can make requirements less strict to allow previous submodules versions in boto3-stubs requirements?

What if you were to switch `boto3-stubs` and `mypy-boto3-*` to a [CalVer](https://calver.org/) scheme like `YYYY.0M.MICRO`? Then on nightly builds, you release a particular `mypy-boto3-*` package if either of the two following conditions are satisfied:
* There is a change to the generated code.
* The date of the last release is >= 3 months old.

Then in the requirements for `boto3-stubs` you allow `mypy-boto3-*` packages which are >= the version of boto3-stubs minus 4 months.

I think this would make the release process much more efficient and flexible. What do you think?

**Comment by vemel** [comment]
Yes, in the next version I plan to allow older subpackages and main package versions. Strict versions are easier to manage, but harder to use.

**Comment by maresb** [comment]
But does semver even make sense given your workflow?

Do you have any plans to reduce the daily builds of all packages?

**Comment by vemel** [comment]
No, packages will still be released daily, as `boto3` itself. Subpackages versions are the same as the corresponding `boto3` version, so that is why it uses SemVer.

**Comment by vemel** [comment]
@maresb I am working on `mypy-boto3-builder 5.0.0` and it should solve the issue. Should be out this week.

Main changes:

- `boto3-stubs` does not require a specific version of `botocore-stubs`. Some typing issues could appear on the client-side if versions are too diverged
- `mypy-boto3-*` (sub pacakges) do not require a specific version of `boto3-stubs`. The only issue I can see here - for newly added boto3 service autocomplete will not work automatically unless `boto3-stubs` is up to date.
- `boto3-stubs` generated docstrings will point to `latest` `boto3` docs instead of a specific version. This should make links in docstrings consistent even if the underlying `boto3-stubs` package was not updated. Links from sub packages docs will still point to a specific version of `boto3` documentation.

By the way, do you plan to add a package with all submodules installed? `pip install 'boto3-stubs[all]'`

**Comment by maresb** [comment]
Those are some very exciting developments!!!

I'm fairly certain that a `boto3-stubs-all` Conda package is not feasible. In any case I think it would be detrimental to conda-forge. The reason is, you have 270 packages which update once per day. That would be 100,000 packages per year associated with just this single project. Already, `conda`'s solver is unbearably slow, and publishing superfluous packages in those quantities won't help. (The way `mamba`/`conda` works, according to my possibly inaccurate understanding, is that it loads all the dependencies and feeds them to a dependency solver which somehow tries to find a constellation of packages which are simultaneously all compatible with each other and are optimally up-to-date. This is computationally a very difficult problem.)

I don't really have any quantitative sense for what the impact would actually be. *I may well be wrong, and maybe it's not actually a major problem*. (We'd have to consult people who are more expert than me.) But currently I feel quite bad for the burden we're placing on the system.

An example I've recently seen where a feedstock with too many packages has become (very mildly) problematic is [DVC](https://github.com/conda-forge/dvc-feedstock/). If you look at the "Current release info", the badges in the first row are broken because the metadata is so huge. And they only publish on the order of once per month.

That's why I'm so interested in only updating the packages which actually change. I'm curious if you know this statistic: in your daily rebuilds, in how many of the 270 packages actually have changes?

**Comment by vemel** [comment]
Around 5-10 packages are actually changed. Sometimes when there are changes in boto3 itself, all packages have to be changed. I do not know what is the best way to check if package should be updated and released on `boto3` release.

- I can diff files after package generation
- Or I can trust boto3 changelogs and release only mentioned packages

**Comment by maresb** [comment]
If we could get it down to 5-10 packages per day, then I'd think that a release for all packages should be doable. It'd probably be worthwhile to discuss with the conda-forge maintainers to see if they have any advice for such a large undertaking.

I don't really have any idea how your package actually works internally... how serious is it when boto3 and boto3-stubs are not exactly in sync? Would everything be broken, or is it just that there are occasional tiny API changes that 99% of developers would never notice?

How often are the changes where everything has to be rebuilt due to a boto3 change? Are those the minor releases? I currently see minor 17 and patch 104, so does that mean that it's been 104 days since the last minor release, and there have been 17 minor releases so far?

Just thinking out loud with a few ideas...

It looks to me like the `boto3-stubs` package consists of two parts:
1. Some core functionality related to `boto3` itself
2. The metapackage where you define `extras_require` for `all` and `essential`.

Would it make sense to split these parts into two separate packages? (I feel like that would help in order to decouple the dependencies and the code.)

I wonder if it would make sense to create a separate GitHub repo per `mypy-boto3-*` for the `mypy-boto3-builder`-rendered code, and then maybe set them up as git submodules in a master repo. Then each day you could
* run `mypy-boto-builder` the master repo
* iterate through each `mypy-boto3-*` git-submodule
  - git commit / push if there are changes

Then each `mypy-boto3-*` repo could have its own CI script to bump the version number and make a PyPI release whenever there is a commit.

**Comment by vemel** [comment]
There are some changes I have to make in order to release only packages with changes. Even if a boto3 service was not updated, there will be changes due to doc links and documentation. So I have to somehow explude them from comparison. 

Packages generated by `mypy-boto3-builder`:
- `botocore-stubs` - static annotations for botocore, dependency of `btoto3-stubs`
- `boto3-stubs` - static annotations for boto3, generated annotations for boto3 and overloads for each boto3 service client/resource autocomplete/type checking, dependency of all subpackages
- `mypy-boto3-<service_name>` - generated annotations for a specific boto3 service

I have just come up with the idea to compare botocore service schema to find changes instead of comparing generated package. If underlying jsonschema is the same for current and previous version of botocore - package is obviously the same and should not be generated and published. However, this way I have to somehow have two `botocore` versions installed or at least have old chemas.

**Comment by maresb** [comment]
That sounds very promising! (Although I don't understand the details about the json schema management.)

I think individual packages will be the way to go if you succeed with the release-on-change plan. Thus I'll leave the conda-forge recipes as-is for now. Thanks so much for considering this, and best of luck!

**Comment by maresb** [comment]
I [asked the conda-forge maintainers on Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=60e035f4bcb3e8060ef9d30f). @chrissburr responds with:

> You're right to be worried and distributing nightly builds isn't allowed as the infrastructure can't handle it if many packages try to. Is there a need to distribute them all separately? I guess these are all pretty lightweight and the versions are changed in sync? If so, so could boto3-stubs just install everything instead of trying to split it into hundreds of different packages?

That's an interesting question. Do you know how big `boto3-stubs[all]` would be as a single package?

**Comment by maresb** [comment]
@chrisburr, thanks for the I did a quick check in my site-packages directory after pip installing `boto3-stubs[all]` and it seems to be about 84M.

@vemel, sorry for the potentially silly question... I noticed that all files seem to be triplicated in my site-packages: once as `.pyi`, once as `.py`, and once as `.pyc`. I notice that the mypy typeshed contains only `.pyi` files. Are the `.py` and `.pyc` files necessary for something? (If not, you could probably trim things down to 28M!)

**Comment by maresb** [comment]
@chrisburr, it seems to me like we could add to `update_upstream_versions:get_latest_version` something like 

```python
if datetime.now().weekday() != 6:
    return version_data
```

to auto-tick only on Sundays, right?

**Comment by vemel** [comment]
Both pyi files are used for type checking and aurocomplete. Py files are exactly the same, but users can use types from them in their code.

Without py files the library loses some functionality, it provides only type checking and autocomplete.

**Comment by vemel** [comment]
One week later than expected, I released `mypy-boto3-builder 5.0.0`, so the next `boto3-stubs` should be safe to build for `conda-forge`.

THank you for your help!

**Comment by maresb** [comment]
Excellent @vemel!

I have [an ugly patch](https://github.com/conda-forge/boto3-stubs-feedstock/pull/58/files) which should pin the dependencies to 5 patch versions back and newer.

I have set it so that there is no upper limit, so `boto3-stubs 1.17.112` would allow installation of `mypy-boto3-s3 1.18.0`. Is that desired?

Once `1.17.112` comes out, would you like me to close this issue and open a new one for non-daily builds?

**Comment by vemel** [comment]
@maresb there will be an issue with packaging today, because `boto3-stubs` require the same minor version for subpackages, and `boto3 1.18.0` was released. So, this issue will still appear on any minor/major release of `boto3`.

What do you think?

**Comment by maresb** [comment]
Ah, let's see what happens, but I think my code should handle this. I go back 5 *patch* versions and take max with 0.

**Comment by maresb** [comment]
Great, it worked this time after restarting manually. But next time there should be compatible versions so that no restart will be necessary until the next minor version.

**Comment by vemel** [comment]
Awesome, man! Thanks for your help. I am closing the issue then.
