### ISSUE TITLE
[BUG] StreamingBody not compatible with SupportsRead[Union[str, bytes]]

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#88]
**Describe the bug**
This would allow things like `json.load(s3_response_body)` to pass `mypy` checks.

**To Reproduce**
1. Install `boto3-stubs = {version = "*", extras = ["batch", "dynamodb", "lambda", "lambda-python", "s3", "s3control", "sqs", "ssm", "stepfunctions", "sts"]}` with Poetry
2.  Run mypy on the following code sample

```python
from json import load

import boto3

get_object_response = boto3.client("s3").get_object(Bucket="foo", Key="bar")

metadata = load(get_object_response["Body"])
```
3. Actual mypy output

```
test.py:7: error: Argument 1 to "load" has incompatible type "StreamingBody"; expected "SupportsRead[Union[str, bytes]]"  [arg-type]
test.py:7: note: Following member(s) of "StreamingBody" have conflicts:
test.py:7: note:     Expected:
test.py:7: note:         def read(self, int = ...) -> Union[str, bytes]
test.py:7: note:     Got:
test.py:7: note:         def read(self, amt: Optional[str] = ...) -> bytes
Found 1 error in 1 file (checked 1 source file)
```

**Expected mypy-output**

None.

**Additional context**
Arch Linux, boto3-stubs 1.17.94, boto3 1.17.53, mypy 0.812 and 0.902.

**Comment by vemel** [comment]
Yes, `StreamingBody` should implement `SupportsRead` interface. I will add it.

**Comment by vemel** [comment]
This was fixed 4 days ago. Please make sure you have the latest version of `boto3-stubs` and `botocore-stubs` installed. Looks like `botocore-stubs` is outdated.

**Comment by l0b0** [comment]
You're right, sorry for the noise. I'd upgraded botocore-stubs to 1.20.92 rather than 1.20.94.
