### ISSUE TITLE
[BUG] StreamingBody not compatible with IO[bytes]

### ISSUE THREAD

**Issue by l0b0** [vemel/mypy_boto3_builder#89]
**Describe the bug**

As in the title.

**To Reproduce**
1. Install `boto3-stubs = {version = "*", extras = ["s3"]}` (1.17.97) with Poetry
2.  Run mypy on the following code sample

```python
import boto3
from mypy_boto3_s3 import S3Client

client: S3Client = boto3.client("s3")

get_object_response = client.get_object(Bucket="foo", Key="bar")

client.put_object(Bucket="foo", Key="baz", Body=get_object_response["Body"])
```
3. Actual mypy output

```
test.py:7: error: Argument "Body" to "put_object" of "S3Client" has incompatible type "StreamingBody"; expected "Union[bytes, IO[bytes]]"  [arg-type]
```

**Expected mypy-output**

None.

**Additional context**
Running mypy 0.902 on Arch Linux.

Workaround: `# type: ignore[arg-type]`

Edit: Is this [something which has to be fixed upstream](https://github.com/boto/boto3/issues/426)?

**Comment by vemel** [comment]
Thank you! I will investigate. It should be compatible with `IO[bytes]`

**Comment by vemel** [comment]
I released a fix. It should be applied once `boto3 1.17.99` is out. So, let's test it tomorrow and let me know if it works as expected.

**Comment by l0b0** [comment]
I'll know tomorrow when Dependabot tries to update everything.
