### ISSUE TITLE
resources.collection.pages() annotation

### ISSUE THREAD

**Issue by arnimarj** [vemel/mypy_boto3_builder#9]
It seems that `pages()` for a given resource collection is annotated with a return type of `Iterator[ResourceType]`. The documentation at https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/collections.html#boto3.resources.collection.CollectionManager.pages says that it returns a generator which yields iterables of the given resources, somthing like `Generator[Iterable[resource], None, None]` I think

The documentation seems to contradict itself when it says:

```
Return type
   list(ServiceResource)
```

EDIT:

The boto3 codebase seems to be yielding Lists: https://github.com/boto/boto3/blob/0cc6042615fd44c6822bd5be5a4019d0901e5dd2/boto3/resources/collection.py#L177

**Comment by vemel** [comment]
So, it should be `Generator[List[ResourceType], None, None]`. Thank you!

**Comment by vemel** [comment]
Should be fixed in the latest `boto3-stubs==1.12.28.1`. I also recommend to update `boto3` to `1.12.28` to keep type annotations consistent.

Please let me know if the issue still exists or if you find something related.

**Comment by arnimarj** [comment]
Verified to work for my use-case :)
