### ISSUE TITLE
Add types for Requests

### ISSUE THREAD

**Issue by jonathanmorley** [vemel/mypy_boto3_builder#90]
Due to #64, I often create a dict of params to pass into a boto3 client function call, add entries to that dict if necessary, then use it as a kwargs to the function call.

For example:

```
params = {"TargetGroupArn": tg_arn}
    if targets:
        params["Targets"] = targets
return elbv2_client.describe_target_health(**params)
```

The trouble is, I can't easily use `mypy_boto3` types to declare the type of the params variable, and end up having to create my own based on the function signature. E.g.

```
class DescribeTargetHealthRequestTypeDef(TypedDict, total=False):
    TargetGroupArn: str
    Targets: List[TargetDescriptionTypeDef]

params: DescribeTargetHealthRequestTypeDef = {"TargetGroupArn": tg_arn}
...
```

This works well, but it would be better if `mypy_boto3` exposed types like these, rather than consumers needing to individually define them.

I understand that these types cannot be used in the actual function signatures until we have something like `Expand` (From https://github.com/python/mypy/issues/4441), but just having a compatible `TypedDict` appears to be enough to satisfy typechecking.

**Comment by vemel** [comment]
This is doable. However, I have to check if it is possible to use request typed dicts with type annotated `boto3` functions.

Anyway, I can add a generation of Request TypedDefs from Request shapes.

**Comment by vemel** [comment]
I have just released a new builder version that adds `...RequestTypeDef` types, so they should be usable now. Luckily, I found a couple of bugs created to type defs name clash while implementing this feature. Check the changelog https://github.com/vemel/mypy_boto3_builder/releases/tag/4.19.0 .

`boto3-stubs 1.17.102` with RequestTypeDefs should be released tomorrow, so please let me know if the implementation suits your needs.

**Comment by vemel** [comment]
Version `1.17.101.post1` released with `RequestTypeDef` 's and multiple bugfixes. Let me know how it works for you!

**Comment by roberthl** [comment]
It appears this release unintentionally changes the `...ResponseTypeDef` types `...ResponseResponseTypeDef`.

For example, in `mypy_boto3_glue/type_defs.py` (comparing `1.17.101` and `1.17.101.post1`):
```diff
__all__ = (
    "ActionTypeDef",
    "BackfillErrorTypeDef",
-    "BatchCreatePartitionResponseTypeDef",
-    "BatchDeleteConnectionResponseTypeDef",
-    "BatchDeletePartitionResponseTypeDef",
-    "BatchDeleteTableResponseTypeDef",
-    "BatchDeleteTableVersionResponseTypeDef",
-    "BatchGetCrawlersResponseTypeDef",
-    "BatchGetDevEndpointsResponseTypeDef",
-    "BatchGetJobsResponseTypeDef",
-    "BatchGetPartitionResponseTypeDef",
-    "BatchGetTriggersResponseTypeDef",
-    "BatchGetWorkflowsResponseTypeDef",
+    "BatchCreatePartitionRequestTypeDef",
+    "BatchCreatePartitionResponseResponseTypeDef",
+    "BatchDeleteConnectionRequestTypeDef",
+    "BatchDeleteConnectionResponseResponseTypeDef",
+    "BatchDeletePartitionRequestTypeDef",
+    "BatchDeletePartitionResponseResponseTypeDef",
+    "BatchDeleteTableRequestTypeDef",
+    "BatchDeleteTableResponseResponseTypeDef",
+    "BatchDeleteTableVersionRequestTypeDef",
+    "BatchDeleteTableVersionResponseResponseTypeDef",
+    "BatchGetCrawlersRequestTypeDef",
+    "BatchGetCrawlersResponseResponseTypeDef",
+    "BatchGetDevEndpointsRequestTypeDef",
+    "BatchGetDevEndpointsResponseResponseTypeDef",
+    "BatchGetJobsRequestTypeDef",
+    "BatchGetJobsResponseResponseTypeDef",
+    "BatchGetPartitionRequestTypeDef",
+    "BatchGetPartitionResponseResponseTypeDef",
+    "BatchGetTriggersRequestTypeDef",
+    "BatchGetTriggersResponseResponseTypeDef",
+    "BatchGetWorkflowsRequestTypeDef",
+    "BatchGetWorkflowsResponseResponseTypeDef",
...
```

**Comment by vemel** [comment]
It is an intentional change, please see the changelog: https://github.com/vemel/mypy_boto3_builder/releases/tag/4.19.0 generate two different TypedDicts, one with `ResponseMetadata` and the other one without. To avoid name conflicts, I added `ResponseTypeDef` postfix to all response Shapes.

**Comment by roberthl** [comment]
Thanks for clarifying, I understand the reason behind the change.

It's unfortunate that this breaking change ends up in a sub-patch release, but I realize you keep the version in sync with boto3.

Is there a way for libraries that depend on this library to avoid breaking changes upstream, without specifying an overly specific version of mypy-boto3?

**Comment by vemel** [comment]
Yes, for `mypy-boto3-builder` in was a minor release. Built packages versions are in sync with `boto3`.

I do not expect any breaking changes anytime soon. Actually, let me check if this change was really needed. I noticed some conflicts in `s3` module annotations, but probably they can be avoided somehow.

**Comment by vemel** [comment]
@roberthl  @jonathanmorley I am partially reverting the change in the upcoming `4.21.0`

```
### Notes

TypeDefs changes introduced in `4.19.0` were too dramatic. In order to keep the package as backward-compatible as possible, TypeDefs changes are reverted.

Unfortunately, there is no way to keep things as they were because older versions used to add `ResponseMetadata` to TypeDefs that do not include it. So, this version adds `ResponseMetadataTypeDef` postfix to Response TypeDef only if there is a conflict. So, it should still be way closer to pre-`4.19.0` releases.

New packages `boto3-stubs 1.17.101.post2` and `boto3-stubs 1.17.102.post1` will be released shortly after.

### Changed
- `[services]` Reverted `ResponseTypeDef` postfix for all Response Shapes from `4.19.0`
- `[services]` If both Shape and Response Shape  are required, Response TypeDef gets `ResponseMetadataTypeDef` postfix
```

**Comment by roberthl** [comment]
@vemel This change works for me, appreciate it. Cheers for all your work on this important package.

**Comment by vemel** [comment]
You are welcome. Now changes should be fully backward-compatible. Let me know if you encounter any issues

**Comment by jonathanmorley** [comment]
The new RequestTypeDefs have double `Request` in the name. E.g.

```
from mypy_boto3_acm.type_defs import ExportCertificateRequestRequestTypeDef
```

was this intentional?
