### ISSUE TITLE
boto3-stubs not working in platform Linux but working in platform Darwin

### ISSUE THREAD

**Issue by rajdeep87** [vemel/mypy_boto3_builder#94]
**Describe the bug**
boto3-stubs not working in platform Linux but working in platform Darwin. 
Linux version: **centos rhel fedora**
boto3-stubs is available at https://pypi.org/project/boto3-stubs/

**To Reproduce**
1.  python3.7 -m pip install boto3-stubs
2. Install pyright --  pyright 1.1.152 
2.  Run pyright on the following code sample: 
     command: ~/.nvm/versions/node/v16.4.0/bin/pyright file.py

```python
import boto3
sts_client = boto3.client('sts',
                              region_name='us-west-2',
                              endpoint_url='https://sts.us-west-2.amazonaws.com/',
                              aws_access_key_id=access_key,
                              aws_secret_access_key=secret_key)
reveal_type(sts_client)
s3_client = boto3.client('s3')
reveal_type(s3_client)
```
3. Actual mypy output

```
No configuration file found.
No pyproject.toml file found.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/local/home/mukherr/temp/temp.py
  file.py:5:49 - error: "access_key" is not defined (reportUndefinedVariable)
  file.py:6:53 - error: "secret_key" is not defined (reportUndefinedVariable)
  file.py:7:13 - info: Type of "sts_client" is "Unknown"
  file.py:9:13 - info: Type of "s3_client" is "Unknown"
2 errors, 0 warnings, 2 infos 
Completed in 1.331sec
```

**Expected mypy-output**

```
file.py:7:13 - info: Type of "sts_client" is "STSClient"
file.py:9:13 - info: Type of "s3_client" is "S3Client"
```

**Additional context**
Your OS - centos rhel fedora
pyright 1.1.152 
Boto3 version 1.17.102
boto3-stubs 1.17.102.post1
installation method: 
    python -m pip install boto3-stubs
    pip install boto3
Location of boto3 stubs: /usr/local/lib/python3.7/site-packages/boto3-stubs/

**Comment by vemel** [comment]
Looks like `sts` and `s3` submodules are not installed, you only have common `boto3-stubs` without any services support. You can install them with

```bash
python -m pip install 'boto3-stubs[sts,s3]' # add any extra boto3 services you use, I added only s3 and sts

pip list | grep '^mypy-boto3' # check if submodules were installed

pyright file.py # run type checking again
```

You can find all available submodules here: https://pypi.org/project/boto3-stubs/#submodules

Let me know if it solves your issue.

**Comment by rajdeep87** [comment]
Perfect. Thanks a lot for the suggestion. The issue is resolved with the installation of the `boto3-stubs` with all services. 
`python -m pip install 'boto3-stubs[all]'`

**Comment by vemel** [comment]
You are welcome!

Be careful if you use PyCharm. Its built-in type checker consumes a lot of RAM with all services installed. `mypy` and `pyright` work without any issues.
