### ISSUE TITLE
TypeError: 'type' object is not subscriptable in service_resource.py

### ISSUE THREAD

**Issue by AGiantSquid** [vemel/mypy_boto3_builder#95]
I got a strange error in while using `boto3-type-annotations` . 

Error: 

```
[ERROR] TypeError: 'type' object is not subscriptable Traceback (most recent call last): 
```

Here is relevant stack trace:

```
     from mypy_boto3_dynamodb.service_resource import Table   
File "/var/task/mypy_boto3_dynamodb/__init__.py", line 48, in <module>
     from .service_resource import DynamoDBServiceResource   
File "/var/task/mypy_boto3_dynamodb/service_resource.py", line 66, in <module> 
    class ServiceResourceTablesCollection(ResourceCollection["Table"])
```

I found a previous version of the code that worked, and in `mypy_boto3_dynamodb.service_resource.py`, line 63, it has:

```
class ServiceResourceTablesCollection(ResourceCollection):
```

In the broken code, `mypy_boto3_dynamodb.service_resource.py`, line 66, it has 

```
class ServiceResourceTablesCollection(ResourceCollection["Table"]):
```

The working version says `__version__ = "1.17.55.0"`

The broken version file says: `__version__ = "1.17.103"`

The code is running in AWS lambda environment in both working and broken example.

I can't find this bit in the source code to see when it changed. Is the file dynamically created based on the boto source code?

**Comment by vemel** [comment]
Hello and thank you for the report!

This was changed two releases ago. I added more explicit type annotations for collections. I will try to find a working solution or rollback this change. This annotation does not help with type checking or autocomplete anyway.

**Comment by vemel** [comment]
I have just released a new version of builder `4.22.1` with the bugfix. Since this is an urgent issue, I am going to release `boto3-stubs 1.17.103.post1` with the hotfix.

**Comment by vemel** [comment]
So, `boto3-stubs 1.17.103.post1` released, so the non-working version was up for only 12 hours. Please date and let me know if it works as expected.

Thank you once again for the report, and for all of the upvotes, so I jumped on this even before my breakfast. It is not very pleasant to start the morning with a rollback hotfix. But on the good side - new integration tests not only run `mypy` and `pyright` as usual to verify type checking, but also to import test files to prevent issues like this one.

So, hopefully, non-working imports are gone for good.

Again, let me know if everything works as it should for you!

**Comment by AGiantSquid** [comment]
I can can confirm that my issue is now resolved. Thank you for the quick action to get this working again!
