### ISSUE TITLE
Release only packages with changes

### ISSUE THREAD

**Issue by maresb** [vemel/mypy_boto3_builder#97]
Currently, otherwise-identical versions of `mypy-boto3-*` packages are uploaded each time the boto3 version number updates. This is blocking the release of "all" packages on conda-forge because there are too many updates.

Hopefully we could implement something like what was suggested in https://github.com/vemel/mypy_boto3_builder/issues/87#issuecomment-873123823 to build packages only when they change.

**Comment by vemel** [comment]
Finally, `mypy-boto3-builder` supports building only packages that have changed in the current `boto3` release! I am going to update CI to release only updated packages. 

- On a micro `boto3` release only updated packages and `boto3-stubs` are updated
- On a minor `boto3` release all packages are released just in case
- On any major changes in `mypy-boto3-builder` all packages are released
- `boto3-stubs` requires current minor release of subpackages (`>=1.19.0`)

**Comment by maresb** [comment]
@vemel that is excellent news!!! Thank you so much for rolling this out. Let's see how this goes in the coming days, and then we can think about doing a conda-forge release for "all".

**Comment by vemel** [comment]
Finally, the new `mypy-boto3-builder` was released. Today is the last day when I build all packages. Starting from tomorrow I am going to build only updated packages. On minor `boto3` releases or on `mypy-boto3-builder` fixes, I am going to still release all packages.

**Comment by vemel** [comment]
Tomorrow I will release only updated packages for the first time. I hope it works as it should.

**Comment by maresb** [comment]
Thanks for the update, I hope it goes well!

**Comment by vemel** [comment]
It went well indeed! As you see, only 3 updated sub-packages + 3 master packages were built and published: https://github.com/vemel/mypy_boto3_builder/runs/4158241193?check_suite_focus=true

```
21:53:27 mypy_boto3_builder: INFO     Bulding version 1.20.2
21:53:27 mypy_boto3_builder: INFO     [1/3] Generating mypy_boto3_batch 1.20.2
21:53:30 mypy_boto3_builder: INFO     [2/3] Generating mypy_boto3_health 1.20.2
21:53:31 mypy_boto3_builder: INFO     [3/3] Generating mypy_boto3_greengrassv2 1.20.2
21:53:33 mypy_boto3_builder: INFO     Generating mypy-boto3 1.20.2
21:53:37 mypy_boto3_builder: INFO     Generating boto3-stubs 1.20.2
21:53:52 mypy_boto3_builder: INFO     Generating botocore-stubs 1.23.2
```

Some notes:
- There could still be post-releases, like `mypy_boto3_health 1.20.2.post1`, but in this case `boto3-stubs 1.20.2.post1` will be published as well
- `botocore-stubs` version can also be a post-release
- `boto3-stubs` is still published on every `boto3` release

Please let me if I can help you with updating conda forge templates or CI.

**Comment by maresb** [comment]
That's awesome!!! I'm looking forward to seeing how it goes with the conda-forge autoupdate. Thanks so much for your work on this!

**Comment by vemel** [comment]
Thank you, man! Let's close this issue and create new ones if we discover anything wrong.
